#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv,json,re
from pathlib import Path

GOALS = {'IV/01': ['test complex differentiability at a point by comparing directional difference quotients or the real derivative;',
           'translate between the complex derivative and the corresponding real-linear map;',
           'verify holomorphicity of elementary functions and identify exceptional points where differentiability fails;',
           'apply product, quotient, and chain rules in complex-variable calculations;',
           'construct first-order complex linearizations with a controlled little-o remainder;',
           'produce examples showing why real differentiability alone does not imply complex differentiability;'],
 'IV/02': ['derive the Cauchy--Riemann equations from complex differentiability;',
           'check the Cauchy--Riemann equations for explicit functions and combine them with regularity hypotheses correctly;',
           'reconstruct harmonic conjugates from compatible partial-derivative data;',
           'distinguish necessary Cauchy--Riemann conditions from sufficient conditions for holomorphicity;',
           'express the derivative in terms of real partial derivatives once holomorphicity is established;',
           'construct examples where the Cauchy--Riemann equations hold at a point but complex differentiability still fails;'],
 'IV/03': ['compute radii of convergence for power series and determine behavior at boundary points separately;',
           'differentiate and integrate power series term by term inside their disks of convergence;',
           'derive Taylor coefficients of holomorphic functions from derivatives at the center;',
           'use local power-series expansions to prove analyticity and uniqueness statements;',
           'manipulate standard expansions to obtain new series representations;',
           'identify the nearest singularity controlling the radius of convergence in concrete examples;'],
 'IV/04': ['parameterize piecewise smooth contours and compute complex line integrals directly;',
           'apply contour reversal, concatenation, and reparameterization rules correctly;',
           'estimate contour integrals using the ML inequality;',
           'identify primitives and use them to evaluate path-independent integrals;',
           'distinguish path independence from mere equality along one family of curves;',
           'choose contours adapted to the geometry of the integrand and domain;'],
 'IV/05': ["verify the hypotheses of Cauchy's theorem on simply connected or triangulated domains;",
           'deform contours through holomorphic regions without crossing singularities;',
           'prove vanishing of closed contour integrals from holomorphicity and topology;',
           "identify when multiply connected geometry prevents a direct use of Cauchy's theorem;",
           'construct primitives from path integrals when closed integrals vanish;',
           'analyze counterexamples showing why a puncture or singularity changes the conclusion;'],
 'IV/06': ["apply Cauchy's integral formula to evaluate values and derivatives of holomorphic functions;",
           'derive Cauchy estimates from contour bounds;',
           "use Cauchy's formula to prove infinite differentiability and analyticity;",
           'compute contour integrals containing powers of \\((z-a)^{-1}\\) by matching the correct derivative formula;',
           'choose a circle contained in the domain to optimize an estimate;',
           'use Cauchy estimates to prove Liouville-type or derivative-vanishing consequences;'],
 'IV/07': ['factor zeros of holomorphic functions by their multiplicity;',
           'apply the identity theorem after verifying an accumulation point lies inside the domain;',
           'distinguish isolated zeros from identically vanishing functions;',
           'use local power series to compute zero multiplicity;',
           'prove uniqueness of analytic continuation on connected domains;',
           'construct examples showing why boundary accumulation of zeros does not trigger the identity theorem;'],
 'IV/08': ['construct Laurent expansions on specified annuli and identify the correct convergence region;',
           'compute principal and analytic parts of Laurent series;',
           'derive Laurent coefficients from contour integrals;',
           'choose among geometric-series expansions according to the relative sizes of \\(|z-a|\\);',
           'use Laurent series to classify singular behavior and compute residues;',
           'distinguish expansions of the same function on different annuli;'],
 'IV/09': ['classify isolated singularities as removable, poles, or essential using Laurent coefficients or growth criteria;',
           'determine pole order from local factorizations;',
           'apply removable-singularity theorems from boundedness or vanishing conditions;',
           'use Casorati--Weierstrass or related behavior to recognize essential singularities;',
           'construct local normal forms near poles and removable points;',
           'distinguish singularity classification from global behavior of the function;'],
 'IV/10': ['compute residues at simple and higher-order poles using the most efficient available formula;',
           'apply the residue theorem after identifying all enclosed singularities and contour orientations;',
           'compute residues at infinity and use global residue balance;',
           'use logarithmic derivatives to count zeros and poles with multiplicity;',
           'choose between Laurent expansion, limit, derivative, and partial-fraction methods for residue computation;',
           'audit winding numbers and contour geometry before summing residue contributions;'],
 'IV/11': ['select contour geometries that convert real integrals into residue calculations;',
           'estimate large-arc and small-arc contributions and justify their vanishing limits;',
           'handle even rational integrands with semicircular contours;',
           'use indentation or principal-value contours when poles lie on the real axis;',
           'track orientation and branch choices when extracting the desired real integral;',
           'distinguish ordinary improper integrals from Cauchy principal values;'],
 'IV/12': ['compute winding numbers of explicit closed curves around specified points;',
           'apply the argument principle to count zeros minus poles inside a contour;',
           "derive zero/pole counts from the logarithmic derivative \\(f'/f\\);",
           'track multiplicities correctly in argument-principle calculations;',
           'relate change of argument along a contour to topological winding;',
           'identify failures when the contour passes through zeros or poles;'],
 'IV/13': ['verify Rouché inequalities on a contour and choose the dominant term strategically;',
           "use Rouché's theorem to count zeros in disks, annuli, or half-planes after suitable changes of variable;",
           'compare candidate functions on the boundary rather than throughout the interior;',
           'track multiplicities in the zero count;',
           'combine Rouché with the argument principle when direct estimates are awkward;',
           'construct examples where a non-strict boundary inequality is insufficient for the theorem;'],
 'IV/14': ['construct branches of the logarithm on simply connected domains avoiding the origin;',
           'define branches of powers and roots from a chosen logarithm;',
           'track argument ranges and branch cuts explicitly;',
           'determine how analytic continuation around the origin changes logarithm and root branches;',
           'distinguish local branches from globally single-valued functions;',
           'choose branch cuts adapted to contour-integral and mapping problems;'],
 'IV/15': ['continue analytic germs along paths by overlapping local expansions;',
           'use the identity theorem to prove uniqueness of continuation on overlaps;',
           'identify natural barriers to analytic continuation from singularities or monodromy;',
           'compare continuations along different paths in simply connected and non-simply-connected domains;',
           'construct examples of multivalued continuation such as logarithms or roots;',
           'state precisely when analytic continuation yields a single-valued global function;'],
 'IV/16': ['compute Möbius transformations from images of three points;',
           'determine images of circles and lines under fractional-linear transformations;',
           'use cross ratios to verify invariance and solve mapping constraints;',
           'classify fixed points and normal forms of simple Möbius maps;',
           'construct automorphisms of the disk and upper half-plane;',
           'track the point at infinity correctly in calculations on the Riemann sphere;'],
 'IV/17': ['verify conformality from holomorphicity and nonvanishing derivative;',
           'compute local angle and scale changes from the derivative;',
           'construct conformal equivalences by composing standard maps;',
           'use disk, half-plane, strip, and sector mappings in explicit domain problems;',
           'apply Schwarz-type principles or normalization to constrain conformal maps;',
           'distinguish conformal equivalence from mere homeomorphism;'],
 'IV/18': ['derive Schwarz--Christoffel exponents from polygon interior angles;',
           'construct the derivative of a Schwarz--Christoffel map from prevertices;',
           'identify accessory constants and normalization conditions in polygon-mapping problems;',
           'analyze local behavior near polygon vertices from the power exponents;',
           'map standard half-plane or disk domains to simple polygons;',
           'check orientation and vertex order before interpreting a Schwarz--Christoffel formula;'],
 'IV/19': ['derive the functional equation \\(\\Gamma(z+1)=z\\Gamma(z)\\) from the defining integral;',
           'extend the Gamma function meromorphically using recurrence;',
           'locate poles and compute residues at nonpositive integers;',
           'apply reflection or multiplication identities under the correct hypotheses;',
           'estimate Gamma asymptotics in elementary regimes developed in the chapter;',
           'translate factorial identities into Gamma-function statements and back again;'],
 'IV/20': ['derive the Beta--Gamma relation by a justified change of variables in a double integral;',
           'compute Beta integrals and reduce them to Gamma values;',
           'apply reflection and duplication formulas to simplify special-function expressions;',
           'track convergence conditions on parameters before manipulating integrals;',
           'use analytic continuation to extend identities beyond their initial integral domains;',
           'check special cases against factorial or trigonometric values as consistency tests;'],
 'IV/21': ['choose a branch of the logarithm appropriate for a keyhole contour;',
           'compute the jump of a branch-dependent integrand across the two sides of a cut;',
           'estimate inner- and outer-circle contributions in keyhole contours;',
           'derive real integrals from residue sums and branch discontinuities;',
           'track argument conventions and orientation signs explicitly;',
           'distinguish branch-cut contributions from pole residues;'],
 'IV/22': ['explain how multivalued analytic continuation motivates passing from the plane to a Riemann surface;',
           'construct local coordinate charts that make a multivalued relation single-valued;',
           'identify branch points and sheets in elementary algebraic examples;',
           'translate pathwise analytic continuation into geometric movement on a surface;',
           'distinguish a branched covering from an ordinary covering away from branch points;',
           'relate local analytic data to the global surface obtained by continuation;'],
 'IV/23': ['verify the local lifting property for elementary covering maps;',
           'lift paths and homotopies once a starting point is fixed;',
           'compute monodromy permutations from continuation around loops;',
           'relate deck transformations to symmetries of a covering;',
           'distinguish simply connected base domains from domains with nontrivial monodromy;',
           'use covering-space language to organize branches of logarithms and roots;'],
 'IV/24': ['identify branch points and ramification indices of elementary holomorphic maps;',
           'write local models in the form \\(w=z^e\\) after suitable coordinates;',
           'compute branching data for polynomial and rational maps;',
           'distinguish ramification points upstairs from branch values downstairs;',
           'apply degree counting with multiplicities in branched coverings;',
           'relate local ramification behavior to global topology in examples;'],
 'IV/25': ['construct Riemann surfaces by gluing charts along biholomorphic overlap maps;',
           'verify cocycle compatibility of transition functions on multiple overlaps;',
           'check Hausdorff and manifold conditions in explicit gluing constructions;',
           'build standard surfaces from polygons, annuli, or slit planes;',
           'track how holomorphic functions and differentials transform across glued charts;',
           'distinguish equivalent gluings from genuinely different complex structures;'],
 'IV/26': ['compactify basic noncompact Riemann surfaces by adding points with valid local coordinates;',
           'compute or identify genus from polygonal, covering, or Euler-characteristic data;',
           'distinguish genus zero, one, and higher-genus compact surfaces in standard examples;',
           'relate punctures, compactification points, and meromorphic extension;',
           'use Riemann--Hurwitz-type data where available to constrain genus;',
           'check that the added points produce a compact Riemann surface rather than only a topological compactification;'],
 'IV/27': ['construct a complex torus as \\(\\mathbb C/\\Lambda\\) from a lattice;',
           'choose fundamental parallelograms and identify equivalent boundary points;',
           'verify that holomorphic structure descends through the lattice quotient;',
           'classify lattice changes induced by basis transformations and scaling;',
           'compute basic topological and complex-analytic invariants of the torus;',
           'relate periodic functions on \\(\\mathbb C\\) to meromorphic functions on the torus;'],
 'IV/28': ['verify double periodicity of candidate elliptic functions with respect to a lattice;',
           'use compactness of the torus to prove global constraints on elliptic functions;',
           'count zeros and poles of elliptic functions with multiplicity in a fundamental domain;',
           'apply residue balance to elliptic functions on the torus;',
           'construct elliptic functions from lattice-periodic meromorphic data;',
           'distinguish singly periodic functions from genuinely doubly periodic elliptic functions;'],
 'IV/29': ['construct the Weierstrass \\(\\wp\\)-function from its lattice series and justify convergence on compacta away from the lattice;',
           'derive evenness, double periodicity, and pole structure of \\(\\wp\\);',
           'compute the differential equation satisfied by \\(\\wp\\) and identify the invariants \\(g_2,g_3\\);',
           "use \\(\\wp'\\) and local expansions to analyze zeros and ramification;",
           'relate lattice symmetries to special values of the Weierstrass function;',
           'distinguish the analytic definition of \\(\\wp\\) from the algebraic cubic relation it later parametrizes;'],
 'IV/30': ['derive addition formulas for \\(\\wp\\) and related elliptic functions from analytic identities;',
           'specialize the addition formula to obtain duplication formulas;',
           'track poles and symmetry to verify candidate elliptic identities;',
           'use the identity theorem to prove equality of elliptic functions once principal parts and enough values agree;',
           "translate addition on the torus into algebraic formulas for \\(\\wp\\) and \\(\\wp'\\);",
           'apply addition identities to compute special values or group-law coordinates;'],
 'IV/31': ["verify that \\((\\wp(z),\\wp'(z))\\) lies on the Weierstrass cubic;",
           'extend the Weierstrass parametrization across the lattice class to the point at infinity;',
           'prove that the torus-to-cubic map is bijective and hence biholomorphic under the nonsingularity hypothesis;',
           'identify the point at infinity as the group identity and inversion as \\(z\\mapsto -z\\);',
           'show that torus addition agrees with the chord-and-tangent group law on the cubic;',
           'relate lattice scaling, the invariants \\(g_2,g_3\\), and the genus-one moduli viewpoint;']}
METHODS = {'IV/01': ['Compare the difference quotient along the real and imaginary directions first; if the two limits disagree, complex differentiability '
           'fails immediately.',
           'Write the real derivative matrix and impose commutation with multiplication by \\(i\\); this forces the Cauchy--Riemann form.',
           'Use two distinct approach directions to test whether a proposed derivative is direction-independent.',
           'Holomorphicity is an open-set condition: check complex differentiability at every point of a neighborhood, not just at one point.',
           'For conjugation or modulus, compute directional quotients at the suspected exceptional point before making a global claim.',
           'Apply the algebra rule only after checking denominators stay nonzero where needed.',
           "Subtract \\(f(z_0)+f'(z_0)h\\) and divide the remainder by \\(|h|\\); the quotient must tend to zero.",
           'Use local complex linearity to predict analyticity consequences, but do not invoke power-series machinery before it has been '
           'established.'],
 'IV/02': ['Write \\(f=u+iv\\) and compare derivatives in the \\(x\\)- and \\(y\\)-directions to obtain the Cauchy--Riemann equations.',
           'Check both equations \\(u_x=v_y\\) and \\(u_y=-v_x\\) at the point, then inspect the regularity needed for sufficiency.',
           'Integrate one of the equations to recover a candidate harmonic conjugate, then use the other equation to determine the missing function '
           'of one variable.',
           'The Cauchy--Riemann equations at a single point are only necessary without additional differentiability assumptions; test the remainder '
           'term.',
           "Once holomorphicity is known, compute \\(f'=u_x+iv_x=v_y-iu_y\\) using the most convenient partial derivatives.",
           'Differentiate the Cauchy--Riemann equations once more to show both real and imaginary parts are harmonic when second derivatives exist.',
           'For a harmonic conjugate, verify the compatibility condition by checking that the proposed differential is closed.',
           'To build a counterexample, make the function satisfy Cauchy--Riemann at the origin while its difference quotient depends on direction.'],
 'IV/03': ['Use the root or ratio test on the coefficients to find the radius; analyze points with \\(|z-z_0|=R\\) separately.',
           'Inside a smaller closed disk, uniform convergence justifies termwise differentiation and integration.',
           'The Taylor coefficient is \\(a_n=f^{(n)}(z_0)/n!\\); compute derivatives only after locating the expansion center.',
           'Use the local series to identify the first nonzero coefficient; it controls local zero order and uniqueness.',
           'Rewrite the target into a known geometric, exponential, logarithmic, or binomial series before multiplying or composing expansions.',
           'The nearest singularity in the complex plane bounds the Taylor disk even when the real-variable expression looks harmless.',
           'To prove equality of two analytic expressions, compare their Taylor coefficients on a common disk of convergence.',
           'Do not substitute outside the convergence disk; first determine the annular or disk region where each manipulated series is valid.'],
 'IV/04': ['Parameterize each smooth contour segment \\(z=\\gamma(t)\\) and convert \\(\\int_\\Gamma f(z)dz\\) to \\(\\int '
           "f(\\gamma(t))\\gamma'(t)dt\\).",
           'Reverse orientation by replacing \\(t\\) with the reversed parameter; this changes the sign of the contour integral.',
           'For concatenated paths, split the parameter interval and add the segment integrals.',
           'Apply the ML bound \\(|\\int_\\Gamma fdz|\\le \\max_\\Gamma|f|\\,L(\\Gamma)\\) after estimating both maximum and length.',
           "If \\(F'=f\\), evaluate by \\(F(\\gamma(b))-F(\\gamma(a))\\); this is the quickest path-independence test.",
           'To disprove path independence, compare integrals around two paths whose difference forms a closed loop enclosing a singularity.',
           'Choose contours so that the integrand or parameterization simplifies on each segment rather than forcing one formula globally.',
           'Before any contour deformation, list the singularities and make sure none are crossed.'],
 'IV/05': ["Check holomorphicity on an open set containing the contour and its interior before invoking Cauchy's theorem.",
           'During contour deformation, verify the swept region is free of singularities; homotopy through a puncture is not allowed.',
           'Triangulate or decompose the region so interior edge integrals cancel pairwise.',
           'In a multiply connected region, inspect each hole; closed contour integrals need not vanish around omitted points.',
           'Define a candidate primitive by a path integral from a base point and use vanishing of closed integrals to prove path independence.',
           'For a punctured-domain counterexample, integrate \\(1/z\\) around a loop with nonzero winding number.',
           'Use local primitives on small disks and patch them only when the overlap integrals are consistent.',
           'Separate topology from regularity: holomorphicity alone does not guarantee every closed integral vanishes on a non-simply-connected '
           'domain.'],
 'IV/06': ['Match the integrand to \\(f(z)/(z-a)\\) and check that \\(a\\) lies inside the positively oriented contour.',
           'For higher derivatives, rewrite the denominator as \\((z-a)^{n+1}\\) and use \\(2\\pi i f^{(n)}(a)/n!\\).',
           'Choose a circle centered at \\(a\\) contained in the domain, then bound the Cauchy integral by its maximum modulus.',
           "Cauchy's estimate gives \\(|f^{(n)}(a)|\\le n!M/R^n\\); select \\(R\\) to make the bound useful.",
           'To prove analyticity, expand \\(1/(z-w)\\) geometrically for \\(|w-a|<|z-a|\\) inside the Cauchy formula.',
           'For Liouville-type reasoning, let the radius in a Cauchy estimate tend to infinity while the global bound remains fixed.',
           'If the contour does not wind once around \\(a\\), include the winding number rather than using the simple formula blindly.',
           'Audit whether singularities of the auxiliary function lie inside the chosen contour before differentiating under the formula.'],
 'IV/07': ['Expand near the zero and factor out the first nonzero Taylor term \\((z-a)^m\\); the exponent \\(m\\) is the multiplicity.',
           'If zeros accumulate at an interior point, apply the local power series there; every coefficient must vanish.',
           'The identity theorem requires the accumulation point to lie in the connected domain, not merely on its boundary.',
           'To compare two holomorphic functions, apply the zero theorem to their difference.',
           'A nonzero holomorphic function has isolated zeros; choose a disk containing no other zeros after factoring the local power.',
           'Analytic continuation is unique because two continuations agree on an overlap with an interior accumulation set.',
           'Boundary accumulation gives no identity-theorem conclusion; use an example such as zeros approaching a boundary point.',
           'Track connected components: equality on one component does not automatically propagate to a different component.'],
 'IV/08': ['Locate the singularities relative to the center first; they determine the annuli on which different Laurent expansions are valid.',
           'For \\(|z-a|<R\\), expand denominator factors in positive powers; for \\(|z-a|>R\\), factor out powers of \\(z-a\\) and expand '
           'inversely.',
           'Separate negative powers from nonnegative powers to identify principal and analytic parts.',
           'Use \\(a_n=(2\\pi i)^{-1}\\int f(z)(z-a)^{-n-1}dz\\) on any circle lying inside the annulus.',
           'The coefficient of \\((z-a)^{-1}\\) is the residue; read it directly once the Laurent series is correct.',
           'Do not merge expansions valid on different annuli even if their algebraic expressions look similar.',
           'For rational functions, partial fractions often expose the correct geometric-series expansions immediately.',
           'Check convergence by comparing the geometric ratio magnitude with one on the intended annulus.'],
 'IV/09': ['If all negative Laurent coefficients vanish, the singularity is removable; if finitely many occur, it is a pole; infinitely many signal '
           'essential behavior.',
           'For a pole, factor \\(f(z)=(z-a)^{-m}g(z)\\) with \\(g(a)\\ne0\\) and identify the smallest valid \\(m\\).',
           'A bounded punctured-neighborhood function has a removable singularity; extend it by the Cauchy-limit value.',
           'Use \\((z-a)^mf(z)\\to c\\ne0\\) to certify a pole of order \\(m\\).',
           'For essential singularities, inspect the Laurent principal part or invoke Casorati--Weierstrass only after ruling out removable and pole '
           'cases.',
           'Classification is local: ignore remote poles and zeros when analyzing the singularity at \\(a\\).',
           'Zeros of the reciprocal correspond to poles of the original function; use this to switch perspectives when convenient.',
           'Check whether cancellation removes an apparent singularity before classifying the unreduced formula.'],
 'IV/10': ["At a simple pole of \\(g/h\\), verify \\(h(a)=0\\) and \\(h'(a)\\ne0\\), then use \\(g(a)/h'(a)\\).",
           'For a pole of order \\(m\\), multiply by \\((z-a)^m\\), differentiate \\(m-1\\) times, and evaluate at \\(a\\).',
           'List every singularity inside the contour before computing any residue; missing one pole invalidates the sum.',
           'Include orientation and winding numbers in the residue theorem rather than assuming every contour is positively oriented once.',
           'For a large collection of finite poles, compute the residue at infinity and use total residue zero when it is shorter.',
           "Residues of \\(f'/f\\) equal zero multiplicities minus pole multiplicities; check the contour avoids zeros and poles.",
           'Choose Laurent, limit, derivative, or partial-fraction methods by local pole structure, not by habit.',
           'After summing residues, perform a quick scale or symmetry check on the final contour integral.'],
 'IV/11': ['For an even rational integrand, use an upper semicircle and relate the full real-axis integral to twice the half-line integral if '
           'symmetry permits.',
           'Estimate the arc by ML: bound the integrand on \\(|z|=R\\) and multiply by the arc length before sending \\(R\\to\\infty\\).',
           'If a pole lies on the real axis, indent around it and decide whether the problem asks for an ordinary integral or principal value.',
           'Choose upper or lower half-plane according to the exponential factor so the arc contribution decays.',
           'Track the orientation of small indentation arcs; their residue contribution often carries a half-residue factor.',
           'For trigonometric integrals, substitute \\(z=e^{it}\\), \\(dt=dz/(iz)\\), and convert sine/cosine to rational functions of \\(z\\).',
           'Before closing the contour, check decay degree: the large arc may not vanish for the chosen integrand.',
           'Extract the desired real quantity only after simplifying the complex contour identity and taking real or imaginary parts as needed.'],
 'IV/12': ['Compute winding number as \\((2\\pi i)^{-1}\\int_\\Gamma dz/(z-a)\\) or from net change of argument.',
           'Deform the curve without crossing \\(a\\); winding number stays unchanged under such homotopies.',
           "For the argument principle, apply the residue theorem to \\(f'/f\\) and interpret residues as multiplicities.",
           'Count zeros and poles with multiplicity; a double zero contributes two, not one.',
           'Make sure \\(f\\) has no zeros or poles on the contour before applying the principle.',
           'Track the change of \\(\\arg f(\\Gamma(t))\\); its total increment is \\(2\\pi(N-P)\\).',
           'Use winding numbers around individual poles when the contour is not a simple Jordan curve.',
           "For polynomial root counts, choose a contour on which the leading behavior makes \\(f'/f\\) or Rouché comparison manageable."],
 'IV/13': ['Choose a decomposition \\(f=g+h\\) so that \\(|h|<|g|\\) on the contour; the inequality need not hold inside.',
           'Estimate each term uniformly on the boundary using the contour radius rather than pointwise interior bounds.',
           'Once the strict inequality is proved, transfer the zero count with multiplicity from \\(g\\) to \\(f\\).',
           'If neither term dominates on one contour, change the radius or regroup terms before abandoning Rouché.',
           'Use the theorem on an annulus by comparing zero counts on outer and inner boundaries separately if needed.',
           'Non-strict \\(|h|\\le|g|\\) is not the standard hypothesis; identify where equality could allow zeros on the boundary.',
           'Combine Rouché with a simple model polynomial whose zeros are already known.',
           'After counting, check whether any zeros could lie exactly on the contour; the theorem excludes that situation.'],
 'IV/14': ['Choose a continuous argument range on the domain first; then define \\(\\Log z=\\ln|z|+i\\Arg z\\).',
           'A simply connected domain avoiding zero admits a logarithm branch; verify both topology and omission of zero.',
           'Define \\(z^\\alpha=e^{\\alpha\\Log z}\\) only after fixing the logarithm branch.',
           'For an \\(n\\)-th root, changing the logarithm by \\(2\\pi i\\) multiplies the value by an \\(n\\)-th root of unity.',
           'Analytic continuation once around zero adds \\(2\\pi i\\) to logarithm; track this monodromy explicitly.',
           'Place branch cuts so the contour does not cross them and the argument remains continuous along each side.',
           'Different branch choices differ by integer multiples of \\(2\\pi i\\); use this to compare formulas.',
           'Do not treat a principal branch identity as globally valid across its cut or around the origin.'],
 'IV/15': ['Continue from one disk to the next only where the local analytic representations overlap on a nonempty open set.',
           'Use the identity theorem on overlaps to show that two local continuations must agree there.',
           'Record singularities encountered along the path; they determine where continuation can stop.',
           'To compare two paths, subdivide them into overlapping continuation charts and track the resulting germ at the endpoint.',
           'In a simply connected domain without singular obstructions, path-independence of continuation is the expected monodromy conclusion.',
           'For logarithm or roots, continue around a loop and compare the terminal germ with the initial one to detect monodromy.',
           'Natural boundaries are not just single singular points; test whether every boundary point obstructs continuation.',
           'Separate existence of continuation along each path from single-valuedness after all possible loops.'],
 'IV/16': ['A Möbius map is determined by three distinct source-target pairs; solve it using cross ratios rather than four unknown coefficients when '
           'possible.',
           'Include \\(\\infty\\) by reading the leading-coefficient ratio and denominator zeros on the Riemann sphere.',
           'Circles and lines are generalized circles; verify their images using inverse substitution or cross-ratio reality conditions.',
           'To map the upper half-plane to the disk, send a chosen boundary point to infinity and normalize one interior point.',
           'Automorphisms of the disk have the form phase times \\((z-a)/(1-\\bar a z)\\); enforce the normalization conditions.',
           'Fixed points solve a quadratic equation from \\(T(z)=z\\); include infinity if the degree drops.',
           'Cross ratios are Möbius invariant; compute one on the source and one on the target to verify a proposed map.',
           'Matrix representatives are defined only up to nonzero scalar; do not treat coefficient normalization as geometric data.'],
 'IV/17': ["A holomorphic map is conformal where its derivative is nonzero; compute \\(f'(z_0)\\) before discussing angle preservation.",
           "The derivative locally multiplies by \\(|f'|\\) and rotates by \\(\\arg f'\\); read geometric distortion from that complex number.",
           'Build complicated maps as compositions of translations, scalings, Möbius maps, exponentials, logarithms, and powers.',
           'To map a strip or sector, first straighten it with an exponential or power map, then use a half-plane/disk transformation.',
           'Check injectivity on the chosen domain; a holomorphic local conformal map need not be globally one-to-one.',
           'Normalize conformal maps by fixing enough points before applying uniqueness theorems.',
           'Boundary correspondence may require extra hypotheses; do not infer it solely from interior conformality.',
           'Use harmonic functions or level curves to visualize the map, but verify the analytic formula independently.'],
 'IV/18': ['For a polygon vertex with interior angle \\(\\alpha_k\\pi\\), the Schwarz--Christoffel derivative contributes exponent '
           '\\(\\alpha_k-1\\).',
           'Place prevertices in boundary order before integrating the product formula; wrong ordering changes the polygon.',
           'Use Möbius freedom to fix three prevertices and reduce the number of accessory parameters.',
           'Near a prevertex, integrate \\((z-x_k)^{\\alpha_k-1}\\) to recover the local corner angle.',
           'Determine multiplicative and additive constants from side lengths, orientation, and one base point.',
           'For unbounded polygons, identify which prevertex corresponds to infinity and adjust the exponent bookkeeping.',
           'Check branch choices of the fractional powers along the boundary so side directions are consistent.',
           'Differentiate a candidate map first; verifying the Schwarz--Christoffel derivative is often simpler than integrating explicitly.'],
 'IV/19': ['Integrate by parts in the defining Gamma integral to obtain \\(\\Gamma(z+1)=z\\Gamma(z)\\) in the initial convergence half-plane.',
           'Use recurrence to continue meromorphically leftward one strip at a time.',
           'At \\(z=-n\\), isolate the simple pole using the recurrence and compute its residue from the finite value at \\(z+n+1\\).',
           'For reflection, pair \\(\\Gamma(z)\\Gamma(1-z)\\) with a contour or Beta identity and track the sine factor.',
           'Check \\(\\Gamma(n+1)=n!\\) as a normalization test for any derived identity.',
           'Parameter differentiation under the integral requires a uniform integrable bound; justify it before producing digamma-type formulas.',
           "Separate asymptotic estimates from exact identities; use the chapter's stated regime before applying Stirling-type reasoning.",
           'Locate poles before shifting contours or arguments so recurrence denominators are never divided by zero unnoticed.'],
 'IV/20': ['Start from the Beta integral and use the substitution \\(x=u/(u+v)\\), \\(t=u+v\\) in the corresponding double integral.',
           'Check \\(\\Re a>0\\) and \\(\\Re b>0\\) before using the integral representation of \\(B(a,b)\\).',
           'Once \\(B(a,b)=\\Gamma(a)\\Gamma(b)/\\Gamma(a+b)\\) is established, reduce special integrals algebraically.',
           'Use \\(B(a,b)=B(b,a)\\) as a symmetry check after any substitution.',
           'For duplication formulas, choose parameters that turn a Beta integral into a trigonometric integral with a half-angle substitution.',
           'Analytic continuation can extend an identity after it is proved on a common open parameter domain; invoke uniqueness explicitly.',
           'Track poles of each Gamma factor before cancelling expressions meromorphically.',
           'Test derived formulas at integer or half-integer parameters where Gamma values are known.'],
 'IV/21': ['Fix the branch \\(z^\\alpha=e^{\\alpha\\Log z}\\) and write the argument on the upper and lower sides of the cut explicitly.',
           'Compute the multiplicative jump across the cut before evaluating any residues; it is the source of the real integral factor.',
           'Estimate the small circle using the local exponent near zero and the large circle using decay at infinity.',
           'Orient the two sides of the keyhole in opposite directions and keep the branch values separate.',
           'Choose the cut to align with the desired real integral, usually along the positive or negative real axis.',
           'Residues come from poles away from the cut; branch discontinuities contribute through the contour sides, not as residues.',
           'After the contour limit, solve the resulting algebraic equation for the real integral rather than discarding the branch factor.',
           'Check parameter ranges that make both small- and large-circle estimates vanish.'],
 'IV/22': ['Start with a multivalued function such as \\(\\sqrt z\\) or \\(\\log z\\) and label continuation sheets along paths.',
           'Near a nonbranch point, choose a local coordinate in which one branch is an ordinary holomorphic function.',
           'At a branch point of \\(w^n=z\\), use \\(w\\) as the local coordinate rather than \\(z\\).',
           'Glue local branches along overlaps according to analytic continuation; the surface records which values belong together.',
           'Project the surface to the base plane and identify where the map fails to be an ordinary covering.',
           'Track a loop in the base and see which sheet the lifted path ends on; this is the geometric meaning of monodromy.',
           'Distinguish the analytic surface from a mere collection of cut planes by checking compatible holomorphic charts.',
           'Use the surface to make the originally multivalued expression single-valued by construction.'],
 'IV/23': ['To lift a path, cover it by evenly covered neighborhoods and choose the unique local lift matching the previous endpoint.',
           'Once the starting lift is fixed, uniqueness forces the entire lifted path.',
           'For a loop, record the endpoint permutation of the fiber; composing loops composes these permutations.',
           'Deck transformations permute fibers while commuting with the covering projection; test both conditions.',
           'A simply connected base admits no nontrivial monodromy for a connected ordinary covering with fixed local branch data.',
           'For \\(z\\mapsto z^n\\) on \\(\\mathbb C^*\\), one turn around zero cycles the \\(n\\) roots.',
           'Homotopic loops give the same monodromy when the homotopy stays in the unbranched base.',
           'Separate ordinary covering behavior from branched points, where evenly covered neighborhoods fail.'],
 'IV/24': ['Compute the local derivative order: if \\(f(z)-f(a)=c(z-a)^e+\\cdots\\), then \\(e\\) is the ramification index.',
           'A ramification point lies upstairs; its image is the branch value downstairs.',
           "For a polynomial, critical points \\(f'(z)=0\\) are the finite ramification candidates; inspect multiplicities locally.",
           'Use the local model \\(w=z^e\\) to count how many sheets merge at the branch point.',
           'Degree counting uses multiplicities: a generic fiber has total multiplicity equal to the map degree.',
           'At infinity, switch to coordinates \\(u=1/z\\) and \\(v=1/w\\) before deciding ramification.',
           'Global branching data constrain genus through Riemann--Hurwitz when that theorem is available.',
           "Do not confuse a multiple zero of the function with ramification unless it is interpreted through the map's local degree."],
 'IV/25': ['Write every overlap map explicitly and check it is biholomorphic on the overlap region.',
           'On triple overlaps, verify \\(g_{ij}g_{jk}=g_{ik}\\); this cocycle identity makes chart identifications consistent.',
           'To check Hausdorffness, separate inequivalent points using neighborhoods that survive the quotient.',
           'Polygon edge identifications should be orientation-compatible with the intended complex structure; track the local coordinates near '
           'vertices.',
           'Functions glue only when their local expressions agree after composing with transition maps.',
           'Differentials glue with the derivative of the transition function; check the transformation law on overlaps.',
           'Equivalent refinements or chart changes do not alter the underlying Riemann surface; compare transition atlases.',
           'Watch for quotient identifications that create nonmanifold points; local neighborhoods must still look like disks.'],
 'IV/26': ['To add a point at infinity, find a reciprocal or other coordinate in which the punctured neighborhood becomes a disk around zero.',
           'A meromorphic function extends across a compactification point when its local expression has at worst a pole in the new coordinate.',
           'Compute Euler characteristic from a cell or polygon decomposition, then use \\(\\chi=2-2g\\) for a compact orientable surface.',
           'For a branched covering, combine degree and ramification data to constrain genus via Riemann--Hurwitz.',
           'Adding one point to \\(\\mathbb C\\) gives the sphere because \\(w=1/z\\) supplies the second chart near infinity.',
           'Do not infer compactness from bounded coordinates; prove the added surface is topologically compact.',
           'Track punctures separately from handles: filling punctures changes compactness without necessarily changing genus.',
           'Use known models—sphere, torus, higher-genus polygon—to sanity-check the computed genus.'],
 'IV/27': ['Choose two \\(\\mathbb R\\)-linearly independent periods \\(\\omega_1,\\omega_2\\); their integer span is the lattice.',
           'Represent every torus point by a point in one fundamental parallelogram, with opposite edges identified.',
           'Translations by lattice vectors are holomorphic, so the quotient inherits a well-defined complex atlas.',
           'Changing the lattice basis by an element of \\(SL_2(\\mathbb Z)\\) does not change the underlying lattice.',
           'Scaling the lattice by \\(\\lambda\\ne0\\) gives a biholomorphic torus after scaling the coordinate by \\(\\lambda\\).',
           'A doubly periodic meromorphic function on \\(\\mathbb C\\) descends to a meromorphic function on the compact torus.',
           'Use compactness to rule out nonconstant holomorphic functions on the torus without poles.',
           'Distinguish the lattice basis from the lattice itself; basis-dependent formulas should be checked for modular invariance.'],
 'IV/28': ['Verify both independent periods, not just one, before calling a meromorphic function elliptic.',
           'Integrate over the boundary of a fundamental parallelogram; opposite-edge contributions cancel by periodicity.',
           'The residue theorem on the parallelogram shows the sum of residues in a fundamental domain is zero.',
           'Apply the argument principle to count zeros and poles; periodic boundary cancellation forces equal total multiplicities.',
           'A nonconstant elliptic function must have poles because it descends to a nonconstant meromorphic function on a compact surface.',
           'Construct new elliptic functions from sums, products, derivatives, or rational functions of known elliptic functions.',
           'Shift zeros and poles back into one fundamental domain before counting them.',
           'Check whether apparent periods are primitive; a smaller lattice may reveal additional symmetry but does not destroy ellipticity.'],
 'IV/29': ['Pair lattice points \\(\\omega\\) and \\(-\\omega\\) in the defining series to expose evenness and improve convergence control.',
           "Differentiate the locally uniformly convergent lattice series termwise away from lattice points to obtain \\(\\wp'\\).",
           "Periodicity follows by reindexing the lattice sum; perform the index shift rather than appealing only to the name 'elliptic'.",
           'Near zero, isolate the \\(z^{-2}\\) term and expand the remaining lattice sum holomorphically.',
           'Compare elliptic functions with the same principal parts to derive the differential equation for \\(\\wp\\).',
           'Define \\(g_2\\) and \\(g_3\\) from lattice sums and track their scaling weights under \\(\\Lambda\\mapsto\\lambda\\Lambda\\).',
           "Zeros of \\(\\wp'\\) occur at nontrivial half-period classes; use oddness and periodicity to locate them.",
           'Keep the analytic lattice-series definition separate from the cubic equation until the identity has actually been proved.'],
 'IV/30': ['Form the elliptic function whose poles cancel between the two sides of the proposed addition identity.',
           'After principal parts cancel, the difference is entire on the compact torus and hence constant; evaluate one convenient point to find '
           'the constant.',
           "For the standard \\(\\wp\\) addition formula, use the slope \\((\\wp'(u)-\\wp'(v))/(\\wp(u)-\\wp(v))\\) and track symmetry in \\(u,v\\).",
           'Obtain the duplication formula by taking the limit \\(v\\to u\\) rather than substituting into a singular expression directly.',
           "Check parity: \\(\\wp\\) is even and \\(\\wp'\\) is odd, which simplifies many addition identities.",
           'Translate \\(u+v\\) on the torus into the third intersection point of a line with the cubic only after the cubic parametrization is '
           'established.',
           'Use pole locations to decide where a candidate formula can be analytically continued across apparent singular denominators.',
           'Verify special cases such as \\(v=-u\\) or half-periods as consistency checks on signs and constants.'],
 'IV/31': ["Substitute \\(x=\\wp(z)\\), \\(y=\\wp'(z)\\) into the differential equation before doing any projective geometry.",
           "Near the lattice origin, use \\(\\wp(z)=z^{-2}+O(z^2)\\) and \\(\\wp'(z)=-2z^{-3}+O(z)\\) to identify the limiting projective point.",
           'The discriminant condition \\(g_2^3-27g_3^2\\ne0\\) is what guarantees the cubic is smooth; check it before invoking compact '
           'Riemann-surface arguments.',
           "To prove injectivity, use that the pair \\((\\wp,\\wp')\\) separates points modulo the lattice, not \\(\\wp\\) alone.",
           'A nonconstant holomorphic map from a compact surface has closed image; combine this with openness to obtain surjectivity onto the '
           'connected cubic.',
           'Once the map is a holomorphic bijection between compact Riemann surfaces, use the standard inverse-holomorphicity theorem for '
           'biholomorphism.',
           "Under inversion \\(z\\mapsto-z\\), \\(\\wp\\) is unchanged and \\(\\wp'\\) changes sign; this matches the cubic group inverse.",
           'Use the addition formula to compare torus addition with the chord-and-tangent coordinates, including the point at infinity as identity.']}

TRIAD=re.compile(
    r"(?P<exercise_block>\\begin\{exercise\}\\label\{exr:iv(?P<ch>\d{2})-(?P<idx>\d{2})\}(?P<exercise>.*?)\\end\{exercise\}\s*)"
    r"(?P<hint_block>\\begin\{hint\}(?P<hint>.*?)\\end\{hint\}\s*)"
    r"(?P<solution_block>\\begin\{solution\}(?P<solution>.*?)\\end\{solution\})",
    re.S,
)

def read_status(repo):
    with (repo/"editorial/CHAPTER_STATUS.tsv").open("r",encoding="utf-8-sig",newline="") as f:
        return list(csv.DictReader(f,delimiter="\t"))

def paths(repo):
    out={}
    for r in read_status(repo):
        c=(r.get("chapter_code") or "").strip()
        if c in GOALS:
            if r.get("status")!="FROZEN" or r.get("next_action")!="COMPLETE":
                raise RuntimeError(f"{c}: expected FROZEN/COMPLETE")
            out[c]=repo/r["canonical_path"]
    missing=sorted(set(GOALS)-set(out))
    if missing: raise RuntimeError(f"missing Volume IV status rows: {missing}")
    return out

def replace_goals(text,code):
    block=[r"\section*{Learning goals}","After this chapter, the reader should be able to:",r"\begin{itemize}"]
    block += [rf"\item {x}" for x in GOALS[code]]
    block += [r"\end{itemize}",""]
    rep="\n".join(block)
    rx=re.compile(r"\\section\*\{Learning goals\}.*?(?=\\section\*\{Conceptual roadmap\})",re.S)
    if not rx.search(text): raise RuntimeError(f"{code}: goals block missing")
    return rx.sub(lambda _:rep,text,count=1)

def replace_hints(text,code):
    n=0; ch=int(code.split("/")[1])
    def repl(m):
        nonlocal n
        if int(m.group("ch"))!=ch:return m.group(0)
        idx=int(m.group("idx")); n+=1
        return m.group("exercise_block")+"\\begin{hint}\n"+METHODS[code][idx-1]+"\n\\end{hint}\n"+m.group("solution_block")
    return TRIAD.sub(repl,text),n

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--repo",required=True)
    ap.add_argument("--mode",choices=("goals","hints","all"),required=True)
    ap.add_argument("--start",type=int,default=1)
    ap.add_argument("--end",type=int,default=31)
    a=ap.parse_args(); repo=Path(a.repo).resolve(); pp=paths(repo)
    summary=[]
    for i in range(a.start,a.end+1):
        code=f"IV/{i:02d}"; p=pp[code]; text=p.read_text(encoding="utf-8-sig"); before=text; h=0
        if a.mode in ("goals","all"):text=replace_goals(text,code)
        if a.mode in ("hints","all"):
            text,h=replace_hints(text,code)
            if h!=8:raise RuntimeError(f"{code}: expected 8 hints, replaced {h}")
        if text!=before:p.write_text(text.rstrip()+"\n",encoding="utf-8")
        summary.append({"chapter_code":code,"changed":text!=before,"hints_replaced":h})
    print(json.dumps(summary,indent=2,ensure_ascii=False))
    return 0
if __name__=="__main__":raise SystemExit(main())
