#!/usr/bin/env python3
"""GA-03g.3: focused, conservative homological-algebra consistency review.

Read-only unless --apply. --apply writes ONLY a new TSV and Markdown report.
Does not modify chapter content, imported inventory, GA-03f, or GA-03g.1/.2.
Mathematical assessments are curated judgments and remain explicitly distinct
from automated syntax/statement checks. No automatic provenance assertions.
"""
import argparse
import csv
import hashlib
import re
import sys
from pathlib import Path

CHAPTER = Path('books/companion_problems_solutions/chapters/part05_volume_v/chapter.tex')
REPORTS = Path('reports/companion/global_audit')

# Status comes from mathematical review; anchors test for accidental source drift.
CASES = [
    ('CP-V-0041', 'PERIODIC_RESOLUTION', 'CONSISTENT',
     'For A=k[x,y]/(xy), d1=(x y), d2=diag(y,x), d3=diag(x,y); ranks 1,2,2,... give Tor_0(k,k)=k, Tor_i(k,k)=k^2 for i>=1. Ext^1_A(k,A)=k, Ext^i=0 for i!=1.',
     [r'\\ker d_1=(y)\\times(x)', r'\\operatorname{Tor}_i^A(k,k)\\cong k^2', r'\\operatorname{Ext}_A^1(k,A)\\cong k']),
    ('CP-V-0042', 'MINIMAL_RESOLUTION_EXISTENCE', 'CONSISTENT',
     'Repeated minimal free covers are possible since the ring is Noetherian local and each successive kernel is finitely generated; all matrices have entries in the maximal ideal.',
     [r'K_1:=\\ker',r'\\mathfrak mF_0',r'd_2\\otimes_Ak=0']),
    ('CP-V-0043', 'BETTI_AND_PROJECTIVE_DIMENSION', 'CONSISTENT',
     'In a minimal finite-free resolution, differential maps vanish modulo m; beta_i=dim_k Tor_i(k,M)=rank F_i. When pd M is finite, the last nonzero beta index equals pd M.',
     [r'\\operatorname{Tor}_i^A(k,M)',r'\\operatorname{Tor}_{n+1}^A(k,M)=0']),
    ('CP-V-0111', 'SCHANUEL_STABILITY', 'CONSISTENT_WITH_DISTINCTION',
     'Pullback gives K + Fprime ≅ Kprime + F; stable syzygy equivalence does not imply equality of arbitrary free resolution terms or Betti numbers.',
     [r'K\\oplus F\u0027\\cong K\u0027\\oplus F',r'\\cong K\\oplus F\u0027']),
    ('CP-V-0112', 'EXPLICIT_SYZYGIES', 'CONSISTENT',
     'For (x^2,xy,y^2) in k[x,y], the syzygy module is generated by (-y,x,0) and (0,-y,x); distinct from the Koszul resolution of k in CP-V-0079.',
     [r'(-y,x,0)',r'(0,-y,x)']),
    ('CP-V-0045', 'MINIMALITY_EXT_MAP', 'CONSISTENT',
     'Maps represented by matrices with entries in m induce zero on Ext_A^i(k,-), since m annihilates Ext_A^i(k,A) for the commutative local ring.',
     [r'\\operatorname{im}f\\subseteq\\mathfrak mF',r'f_*=0']),
    ('CP-V-0044', 'AUSLANDER_BUCHSBAUM', 'CONSISTENT_WITH_HYPOTHESES',
     'Auslander–Buchsbaum requires nonzero finitely generated M, finite projective dimension, and Noetherian local A. CP-V-0041 has pd_A(k)=infinity, so AB is not applied to that module.',
     [r'n=\\operatorname{pd}_A M',r'\\operatorname{depth}K',r'\\operatorname{depth}M=s-n']),
    ('CP-V-0046', 'TOR_LONG_EXACT_SEQUENCE', 'CONSISTENT',
     'The degreewise tensor sequences are exact because the resolving F_i are free/flat; the connecting map comes from the short exact sequence of complexes.',
     [r'\\partial_n',r'F_i\\otimes_A N']),
    ('CP-V-0047', 'CYCLIC_TOR', 'CONSISTENT',
     'The length-one Z-free resolution yields Tor_1^Z(Z/n,N)=N[n], and for N=Z/m the cyclic group of order gcd(n,m).',
     [r'N[n]',r'\\gcd(n,m)']),
    ('CP-V-0048', 'INTERSECTION_FORMULA', 'CONSISTENT',
     'The natural isomorphism Tor_1^A(A/I,A/J)=(I intersection J)/IJ comes from the kernel of I/IJ -> A/J.',
     [r'\\frac{I\\cap J}{IJ}',r'I/IJ']),
    ('CP-V-0113', 'CYCLIC_EXT', 'CONSISTENT_WITH_DOMAIN',
     'For positive integers n,m, Ext_Z^1(Z/n,Z/m)=Z/gcd(n,m). The statement should explicitly impose n,m>=1, as in CP-V-0047.',
     [r'\\operatorname{Ext}^1_',r'\\gcd(n,m)']),
    ('CP-V-0114', 'DERIVED_EXACTNESS', 'CONSISTENT',
     'Tor is the left derived tensor functor, Ext the right derived Hom functor; the long exact sequences encode the respective failure of exactness.',
     [r'\\operatorname{Tor}_1',r'\\operatorname{Ext}_R^1']),
]


def blocks(text):
    pattern = re.compile(r'\\begin\{problem\}\[(CP-V-\d{4})\]([\s\S]*?)\\end\{problem\}\s*\\begin\{solution\}([\s\S]*?)\\end\{solution\}')
    return {m.group(1): (m.group(2), m.group(3), text.count('\n',0,m.start())+1) for m in pattern.finditer(text)}


def main():
    arg = argparse.ArgumentParser()
    arg.add_argument('--repo', type=Path, default=Path('.'))
    arg.add_argument('--apply', action='store_true', help='write new GA03G3 TSV and Markdown reports only')
    args = arg.parse_args()
    repo = args.repo.resolve()
    file = repo/CHAPTER
    if not file.is_file():
        sys.exit('ERROR missing chapter: '+str(file))
    text = file.read_text(encoding='utf-8')
    index = blocks(text)
    records=[]
    for pid,topic,assessment,note,anchors in CASES:
        pair = index.get(pid)
        if pair is None:
            status='FAIL_MISSING_PAIR';miss=anchors;line=''
        else:
            combined=pair[0]+pair[1]
            miss=[x for x in anchors if x not in combined]
            status='REVIEW_ANCHORS' if miss else 'REVIEWED'
            line=pair[2]
        records.append(dict(problem_id=pid,topic=topic,source_line=line,
                            evidence_status=status,mathematical_assessment=assessment,
                            mathematical_note=note,missing_anchors='; '.join(miss)))
    # Problem scope checks are structural, not mathematical theorem-proving.
    print('GA-03g.3 — RESOLUTION & DEPTH REVIEW')
    print('chapter_sha256:',hashlib.sha256(file.read_bytes()).hexdigest())
    print('reviewed cases:',len(records))
    for row in records:
        print(f"{row['evidence_status']:18} {row['problem_id']} {row['topic']}")
    # Editorial observation recorded, but never auto-edited.
    print('EDITORIAL NOTE: CP-V-0113 does not explicitly state n,m>=1; consider a narrow clarification.')
    print('NOTE: all mathematical assessments are human-review judgments; anchor checks are lexical only.')
    if args.apply:
        output = repo/REPORTS
        output.mkdir(parents=True,exist_ok=True)
        tsv = output/'GA03G3_RESOLUTION_DEPTH_REVIEW.tsv'
        with tsv.open('w',encoding='utf-8',newline='') as f:
            writer=csv.DictWriter(f,delimiter='\t',fieldnames=list(records[0]))
            writer.writeheader();writer.writerows(records)
        md=output/'GA03G3_RESOLUTION_DEPTH_REVIEW.md'
        with md.open('w',encoding='utf-8') as f:
            f.write('# GA-03g.3 — Resolution and depth consistency\n\n')
            f.write('Curated mathematical review; lexical anchor verification is not proof certification.\n\n')
            for row in records:
                f.write(f"## {row['problem_id']} — {row['topic']}\n\n")
                f.write(f"**Assessment:** {row['mathematical_assessment']}; **evidence:** {row['evidence_status']}\n\n")
                f.write(row['mathematical_note']+'\n\n')
                if row['missing_anchors']:f.write('Anchors requiring inspection: `'+row['missing_anchors']+'`\n\n')
            f.write('## Editorial clarification\n\nCP-V-0113 should explicitly assume positive integers n,m; this audit does not modify its statement.\n')
        print('WROTE:',tsv)
        print('WROTE:',md)
    else: print('DRY RUN; no files changed')
    if any(r['evidence_status']=='FAIL_MISSING_PAIR' for r in records):sys.exit(1)

if __name__=='__main__': main()
