DATA = {'V/15': {'examples': [{'after_section': 2,
                        'body': 'In $\\mathbb Z$, every ideal is principal. An ascending chain '
                                '$(a_1)\\subseteq(a_2)\\subseteq\\cdots$ corresponds to a descending chain of positive divisors, so '
                                'it cannot strictly increase forever. This is a concrete manifestation of the Noetherian condition.',
                        'title': 'A chain that stabilizes'},
                       {'after_section': 6,
                        'body': 'In $k[x,y]$, the ideal $I=(x^2,xy,y^2)$ is generated by three quadratic monomials. Every '
                                'higher-degree monomial in $I$ is obtained by multiplying one of these generators, illustrating '
                                'finite generation in a Noetherian polynomial ring.',
                        'title': 'Finite generation in a polynomial ideal'},
                       {'after_section': 8,
                        'body': 'Since $k[x,y]$ is Noetherian, the quotient $k[x,y]/(xy)$ is Noetherian. Ideals of the quotient '
                                'correspond to ideals of $k[x,y]$ containing $(xy)$, so finite generation descends through the '
                                'quotient.',
                        'title': 'Quotient remains Noetherian'}],
          'exercises': {'application': [{'hint': 'Translate the question into ascending chains, finite generation, and Hilbert basis '
                                                 'arguments.',
                                         'prompt': 'Why are coordinate rings of affine algebraic sets over a field Noetherian?',
                                         'solution': 'They are quotients of finitely generated polynomial rings.',
                                         'title': 'Finite algebra'},
                                        {'hint': 'Translate the question into ascending chains, finite generation, and Hilbert basis '
                                                 'arguments.',
                                         'prompt': 'What does Noetherian induction replace?',
                                         'solution': 'It replaces induction on integers by induction over strict enlargement of '
                                                     'subobjects.',
                                         'title': 'Induction'}],
                        'challenge': [{'hint': 'State the relevant ring map, module map, or complex before applying the structural '
                                               'theorem.',
                                       'prompt': "Connect 'ACC on submodules' with 'Examples' in one rigorous argument.",
                                       'solution': 'The opening idea is: A module is Noetherian when every ascending chain of '
                                                   'submodules stabilizes. The later viewpoint is: Fields, PID-like rings, polynomial '
                                                   'rings over fields, and many coordinate rings are Noetherian. A complete solution '
                                                   'identifies the structural theorem that links these descriptions and checks its '
                                                   'hypotheses.',
                                       'title': 'Local-global synthesis'},
                                      {'hint': "Use one of the chapter's explicit computations or counterexamples as the test case.",
                                       'prompt': 'Choose one theorem from the chapter, remove one essential hypothesis, and exhibit '
                                                 'or explain a concrete failure.',
                                       'solution': 'The solution must name the removed hypothesis, show exactly which proof step '
                                                   'breaks, and give a concrete algebraic object where the claimed conclusion fails.',
                                       'title': 'Hypothesis audit'}],
                        'proof': [{'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: An $A$-module is Noetherian iff every submodule is finitely generated.',
                                   'solution': 'If every submodule is finite, the union of an ascending chain is finitely generated '
                                               'and therefore contained in one stage. Conversely, if a submodule were not finitely '
                                               'generated, repeatedly adjoining new elements would produce a strictly increasing '
                                               'chain.',
                                   'title': 'Finite-generation criterion proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': "Prove: For $0\\to M'\\to M\\to M''\\to0$, $M$ is Noetherian iff $M'$ and $M''$ are "
                                             'Noetherian.',
                                   'solution': "Submodules of $M'$ and images in $M''$ control any chain in $M$. For the converse, "
                                               'submodules and quotients of a Noetherian module are Noetherian.',
                                   'title': 'Exact-sequence criterion proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: If $A$ is Noetherian, then $A[x]$ is Noetherian.',
                                   'solution': 'For an ideal $I\\subset A[x]$, leading coefficients form an ideal of $A$ and '
                                               'stabilize under finite generation. Choose finitely many polynomials controlling '
                                               'high-degree leading terms and finitely many lower-degree remainders; together they '
                                               'generate $I$.',
                                   'title': 'Hilbert basis theorem proof'},
                                  {'hint': 'Apply the first theorem to obtain its structural description, then verify the second '
                                           "theorem's hypotheses.",
                                   'prompt': 'Prove a corollary that genuinely uses both Finite-generation criterion and '
                                             'Exact-sequence criterion.',
                                   'solution': 'A correct proof explicitly invokes both results, verifies the common hypotheses, and '
                                               'derives a new consequence rather than merely restating either theorem.',
                                   'title': 'Structural synthesis'}],
                        'standard': [{'hint': 'Use ascending chains, finite generation, and Hilbert basis arguments.',
                                      'prompt': 'Does $(8)\\subset(4)\\subset(2)\\subset(1)$ stabilize in $\\mathbb Z$?',
                                      'solution': 'Yes, after reaching $(1)$ no larger proper stage exists.',
                                      'title': 'Chain check'},
                                     {'hint': 'Use ascending chains, finite generation, and Hilbert basis arguments.',
                                      'prompt': 'Give generators for $(x^2,xy,y^2)$.',
                                      'solution': 'The displayed three monomials generate it.',
                                      'title': 'Finite ideal'},
                                     {'hint': 'Use ascending chains, finite generation, and Hilbert basis arguments.',
                                      'prompt': 'Is $k[x]/(x^5)$ Noetherian?',
                                      'solution': 'Yes, it is a quotient of the Noetherian ring $k[x]$.',
                                      'title': 'Quotient'},
                                     {'hint': 'Use ascending chains, finite generation, and Hilbert basis arguments.',
                                      'prompt': 'Is $A^3$ Noetherian when $A$ is Noetherian?',
                                      'solution': 'Yes, finite free modules are Noetherian.',
                                      'title': 'Finite module'},
                                     {'hint': 'Use ascending chains, finite generation, and Hilbert basis arguments.',
                                      'prompt': 'Is $k[x_1,x_2,x_3]$ Noetherian?',
                                      'solution': "Yes, by iterating Hilbert's basis theorem.",
                                      'title': 'Polynomial extension'}],
                        'test': [{'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: $k[x_1,x_2,\\ldots]$ is Noetherian.',
                                  'solution': 'False: $(x_1)\\subset(x_1,x_2)\\subset\\cdots$ never stabilizes.',
                                  'title': 'Infinite polynomial ring'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: A submodule of a Noetherian module need not be finitely generated.',
                                  'solution': 'False: every submodule is finitely generated.',
                                  'title': 'Submodule'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: An arbitrary direct sum of Noetherian modules is Noetherian.',
                                  'solution': 'False; an infinite direct sum of copies of a field has a strictly increasing chain of '
                                              'finite partial sums.',
                                  'title': 'Infinite direct sum'}]}},
 'V/16': {'examples': [{'after_section': 2,
                        'body': 'For $M=\\mathbb Z/12\\mathbb Z$, the localization $M_{(p)}$ is nonzero exactly for $p=2$ or $3$. '
                                'Thus the support consists of the prime ideals $(2)$ and $(3)$ together with primes containing the '
                                'annihilator $(12)$ in the spectrum description.',
                        'title': 'Support of an integer module'},
                       {'after_section': 4,
                        'body': 'For $A=k[x,y]$ and $M=A/(xy)$, one has $\\operatorname{Supp}M=V(xy)=V(x)\\cup V(y)$. The module '
                                'detects the union of the two coordinate axes.',
                        'title': 'Cyclic module support'},
                       {'after_section': 6,
                        'body': 'From $0\\to A/(x)\\to A/(x^2)\\to A/(x)\\to0$, the support of the middle module equals the union of '
                                'the supports of the ends, namely $V(x)$.',
                        'title': 'Support in an exact sequence'}],
          'exercises': {'application': [{'hint': 'Translate the question into annihilators, localization, and support.',
                                         'prompt': 'What geometric set does module support record?',
                                         'solution': 'It records the primes or points where the module remains locally nonzero.',
                                         'title': 'Geometric locus'},
                                        {'hint': 'Translate the question into annihilators, localization, and support.',
                                         'prompt': 'How can support test whether a finite module vanishes on an open region?',
                                         'solution': 'Localize on that region; vanishing is equivalent to absence of support there.',
                                         'title': 'Local vanishing'}],
                        'challenge': [{'hint': 'State the relevant ring map, module map, or complex before applying the structural '
                                               'theorem.',
                                       'prompt': "Connect 'Definition' with 'Geometric role' in one rigorous argument.",
                                       'solution': 'The opening idea is: $\\operatorname{Supp}M=\\{\\mathfrak p:M_{\\mathfrak '
                                                   'p}\\ne0\\}$. The later viewpoint is: Support marks the locus where a sheaf-like '
                                                   'algebraic object is present. A complete solution identifies the structural '
                                                   'theorem that links these descriptions and checks its hypotheses.',
                                       'title': 'Local-global synthesis'},
                                      {'hint': "Use one of the chapter's explicit computations or counterexamples as the test case.",
                                       'prompt': 'Choose one theorem from the chapter, remove one essential hypothesis, and exhibit '
                                                 'or explain a concrete failure.',
                                       'solution': 'The solution must name the removed hypothesis, show exactly which proof step '
                                                   'breaks, and give a concrete algebraic object where the claimed conclusion fails.',
                                       'title': 'Hypothesis audit'}],
                        'proof': [{'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: If $M$ is finitely generated, then '
                                             '$\\operatorname{Supp}M=V(\\operatorname{Ann}M)$.',
                                   'solution': 'If an annihilator element becomes a unit at $\\mathfrak p$, the localized module '
                                               'vanishes. Conversely, if $M_{\\mathfrak p}=0$, finitely many generators are each '
                                               'killed by denominators outside $\\mathfrak p$; their product lies in '
                                               '$\\operatorname{Ann}M$ but outside $\\mathfrak p$.',
                                   'title': 'Support of a finite module proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': "Prove: For $0\\to M'\\to M\\to M''\\to0$, "
                                             "$\\operatorname{Supp}M=\\operatorname{Supp}M'\\cup\\operatorname{Supp}M''$.",
                                   'solution': 'Localize the sequence. Exactness of localization shows the middle localization is '
                                               'zero exactly when both end localizations are zero.',
                                   'title': 'Support in a short exact sequence proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: An $A$-module $M$ is zero iff $M_{\\mathfrak m}=0$ for every maximal ideal '
                                             '$\\mathfrak m$.',
                                   'solution': 'If $m\\ne0$, its annihilator is proper and lies in some maximal ideal $\\mathfrak m$. '
                                               'Then $m/1$ cannot vanish in $M_{\\mathfrak m}$, otherwise an element outside '
                                               '$\\mathfrak m$ would annihilate $m$.',
                                   'title': 'Maximal-local detection proof'},
                                  {'hint': 'Apply the first theorem to obtain its structural description, then verify the second '
                                           "theorem's hypotheses.",
                                   'prompt': 'Prove a corollary that genuinely uses both Support of a finite module and Support in a '
                                             'short exact sequence.',
                                   'solution': 'A correct proof explicitly invokes both results, verifies the common hypotheses, and '
                                               'derives a new consequence rather than merely restating either theorem.',
                                   'title': 'Structural synthesis'}],
                        'standard': [{'hint': 'Use annihilators, localization, and support.',
                                      'prompt': 'Find $\\operatorname{Supp}(A/I)$.',
                                      'solution': 'It is $V(I)$.',
                                      'title': 'Cyclic support'},
                                     {'hint': 'Use annihilators, localization, and support.',
                                      'prompt': 'Find the support of a nonzero finite free $A$-module.',
                                      'solution': 'It is all of $\\operatorname{Spec}A$.',
                                      'title': 'Free support'},
                                     {'hint': 'Use annihilators, localization, and support.',
                                      'prompt': 'Find $\\operatorname{Supp}(0)$.',
                                      'solution': 'It is empty.',
                                      'title': 'Zero support'},
                                     {'hint': 'Use annihilators, localization, and support.',
                                      'prompt': 'Find $\\operatorname{Ann}_{\\mathbb Z}(\\mathbb Z/18)$.',
                                      'solution': 'It is $(18)$.',
                                      'title': 'Annihilator'},
                                     {'hint': 'Use annihilators, localization, and support.',
                                      'prompt': 'Find $\\operatorname{Supp}(M\\oplus N)$.',
                                      'solution': 'It is $\\operatorname{Supp}M\\cup\\operatorname{Supp}N$.',
                                      'title': 'Direct sum'}],
                        'test': [{'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: A nonzero module can have empty support.',
                                  'solution': 'False: some maximal localization is nonzero.',
                                  'title': 'Nonzero global'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: $\\operatorname{Supp}M=V(\\operatorname{Ann}M)$ for every arbitrary '
                                            'module without hypotheses.',
                                  'solution': 'False in this simple form; finite generation is the standard hypothesis.',
                                  'title': 'Finite formula'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: A submodule always has the same support as its ambient module.',
                                  'solution': 'False; its support can be strictly smaller.',
                                  'title': 'Submodule equality'}]}},
 'V/17': {'examples': [{'after_section': 2,
                        'body': 'For $\\mathbb Z/12\\mathbb Z$, the elements of orders $2$ and $3$ have annihilators $(2)$ and $(3)$ '
                                'after choosing appropriate representatives. The associated primes are $(2)$ and $(3)$.',
                        'title': 'Associated primes of a cyclic integer module'},
                       {'after_section': 5,
                        'body': 'Let $A=k[x,y]/(xy)$. The class of $x$ is annihilated by the class of $y$, and conversely. The '
                                'minimal primes $(x)$ and $(y)$ appear naturally as annihilators of suitable elements.',
                        'title': 'A zero-divisor example'},
                       {'after_section': 7,
                        'body': 'For a finitely generated module over a Noetherian ring, every associated prime lies in the support. '
                                'In $A/(x^2)$, the prime $(x)$ is associated and the support is the full closed set $V(x)$.',
                        'title': 'Associated versus support'}],
          'exercises': {'application': [{'hint': 'Translate the question into element annihilators and associated primes.',
                                         'prompt': 'How do associated primes detect zero divisors on a Noetherian module?',
                                         'solution': 'Zero divisors are captured by the union of associated primes.',
                                         'title': 'Zero divisors'},
                                        {'hint': 'Translate the question into element annihilators and associated primes.',
                                         'prompt': 'Why are nonminimal associated primes important geometrically?',
                                         'solution': 'They record embedded algebraic components invisible from the underlying support '
                                                     'alone.',
                                         'title': 'Embedded components'}],
                        'challenge': [{'hint': 'State the relevant ring map, module map, or complex before applying the structural '
                                               'theorem.',
                                       'prompt': "Connect 'Definition' with 'Primary decomposition preview' in one rigorous argument.",
                                       'solution': 'The opening idea is: A prime $\\mathfrak p$ is associated to $M$ if $\\mathfrak '
                                                   'p=\\operatorname{Ann}(m)$ for some $m\\in M$. The later viewpoint is: Associated '
                                                   'primes index components that later appear in primary decompositions. A complete '
                                                   'solution identifies the structural theorem that links these descriptions and '
                                                   'checks its hypotheses.',
                                       'title': 'Local-global synthesis'},
                                      {'hint': "Use one of the chapter's explicit computations or counterexamples as the test case.",
                                       'prompt': 'Choose one theorem from the chapter, remove one essential hypothesis, and exhibit '
                                                 'or explain a concrete failure.',
                                       'solution': 'The solution must name the removed hypothesis, show exactly which proof step '
                                                   'breaks, and give a concrete algebraic object where the claimed conclusion fails.',
                                       'title': 'Hypothesis audit'}],
                        'proof': [{'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: If $M\\ne0$ is finitely generated over a Noetherian ring, then $M$ has an '
                                             'associated prime.',
                                   'solution': 'Choose an annihilator maximal among annihilators of nonzero elements. If $ab$ lies in '
                                               'it and $b$ does not, the annihilator of $bm$ contains the chosen annihilator and also '
                                               '$a$; maximality forces $a$ into the original annihilator, proving primality.',
                                   'title': 'Associated prime existence proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: If $\\mathfrak p\\in\\operatorname{Ass}M$, then $\\mathfrak '
                                             'p\\in\\operatorname{Supp}M$.',
                                   'solution': 'An embedding $A/\\mathfrak p\\hookrightarrow M$ localizes to a nonzero embedding at '
                                               '$\\mathfrak p$, since $(A/\\mathfrak p)_{\\mathfrak p}$ is nonzero.',
                                   'title': 'Associated implies support proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: For a finitely generated module over a Noetherian ring, every prime minimal in '
                                             '$\\operatorname{Supp}M$ lies in $\\operatorname{Ass}M$.',
                                   'solution': 'Localize at the minimal prime. The localized support has only the maximal prime, so '
                                               'an associated prime of the nonzero localized module must be that maximal prime; '
                                               'contract back.',
                                   'title': 'Minimal support primes are associated proof'},
                                  {'hint': 'Apply the first theorem to obtain its structural description, then verify the second '
                                           "theorem's hypotheses.",
                                   'prompt': 'Prove a corollary that genuinely uses both Associated prime existence and Associated '
                                             'implies support.',
                                   'solution': 'A correct proof explicitly invokes both results, verifies the common hypotheses, and '
                                               'derives a new consequence rather than merely restating either theorem.',
                                   'title': 'Structural synthesis'}],
                        'standard': [{'hint': 'Use element annihilators and associated primes.',
                                      'prompt': 'List the associated primes of $\\mathbb Z/18\\mathbb Z$.',
                                      'solution': 'They are $(2)$ and $(3)$.',
                                      'title': 'Integer module'},
                                     {'hint': 'Use element annihilators and associated primes.',
                                      'prompt': 'Find $\\operatorname{Ass}_A(A)$ when $A$ is a domain.',
                                      'solution': 'It contains the zero prime; in the Noetherian domain case it is exactly $(0)$.',
                                      'title': 'Domain'},
                                     {'hint': 'Use element annihilators and associated primes.',
                                      'prompt': 'Find an associated prime of $A/P$ for prime $P$.',
                                      'solution': '$P$ itself.',
                                      'title': 'Cyclic prime'},
                                     {'hint': 'Use element annihilators and associated primes.',
                                      'prompt': 'In $k[x,y]/(xy)$, what annihilates the class of $x$?',
                                      'solution': 'The ideal generated by the class of $y$.',
                                      'title': 'Annihilator element'},
                                     {'hint': 'Use element annihilators and associated primes.',
                                      'prompt': 'Where must an associated prime of $M$ lie?',
                                      'solution': 'In $\\operatorname{Supp}M$.',
                                      'title': 'Support containment'}],
                        'test': [{'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: Every prime in the support is associated.',
                                  'solution': 'False; associated primes are a distinguished finite subset under Noetherian '
                                              'finiteness.',
                                  'title': 'All support primes'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: A nonzero finite module over a Noetherian ring can have no associated '
                                            'prime.',
                                  'solution': 'False.',
                                  'title': 'Empty associated set'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: The annihilator of every nonzero element is prime.',
                                  'solution': 'False; associated primes arise only when such an annihilator happens to be prime.',
                                  'title': 'Annihilator prime'}]}},
 'V/18': {'examples': [{'after_section': 2,
                        'body': 'For $A=\\mathbb Z$ and $I=(p)$, the quotients $A/I^n=\\mathbb Z/p^n\\mathbb Z$ form an inverse '
                                'system. A compatible sequence of residues is a $p$-adic integer in the completion.',
                        'title': 'Successive $p$-adic quotients'},
                       {'after_section': 5,
                        'body': 'The $(x)$-adic completion of $k[x]_{(x)}$ is $k[[x]]$. Modulo $x^n$, a formal power series is '
                                'determined by its polynomial truncation of degree less than $n$.',
                        'title': 'Power-series completion'},
                       {'after_section': 7,
                        'body': 'In a separated $I$-adic topology, $\\bigcap_{n\\ge1}I^n=0$. For $k[x]$ with $I=(x)$, a polynomial '
                                'divisible by every power of $x$ must be zero.',
                        'title': 'Separatedness test'}],
          'exercises': {'application': [{'hint': 'Translate the question into inverse limits, powers of ideals, and adic topology.',
                                         'prompt': 'How does completion encode increasingly accurate congruence data?',
                                         'solution': 'An element is a compatible choice modulo every power $I^n$.',
                                         'title': 'Approximation'},
                                        {'hint': 'Translate the question into inverse limits, powers of ideals, and adic topology.',
                                         'prompt': 'Why is completion useful near a maximal ideal?',
                                         'solution': 'It replaces a local ring by a limit in which formal expansions and '
                                                     'infinitesimal neighborhoods are easier to analyze.',
                                         'title': 'Local algebra'}],
                        'challenge': [{'hint': 'State the relevant ring map, module map, or complex before applying the structural '
                                               'theorem.',
                                       'prompt': "Connect 'I-adic filtration' with 'Comparison with tensor' in one rigorous argument.",
                                       'solution': 'The opening idea is: The powers $M\\supset IM\\supset I^2M\\supset\\cdots$ define '
                                                   'progressively finer congruences. The later viewpoint is: For finitely generated '
                                                   'modules in the Noetherian setting, completion often agrees with tensoring by '
                                                   '$\\widehat A$. A complete solution identifies the structural theorem that links '
                                                   'these descriptions and checks its hypotheses.',
                                       'title': 'Local-global synthesis'},
                                      {'hint': "Use one of the chapter's explicit computations or counterexamples as the test case.",
                                       'prompt': 'Choose one theorem from the chapter, remove one essential hypothesis, and exhibit '
                                                 'or explain a concrete failure.',
                                       'solution': 'The solution must name the removed hypothesis, show exactly which proof step '
                                                   'breaks, and give a concrete algebraic object where the claimed conclusion fails.',
                                       'title': 'Hypothesis audit'}],
                        'proof': [{'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: The I-adic completion of $M$ is the inverse limit $\\varprojlim M/I^nM$.',
                                   'solution': 'A Cauchy-compatible system is exactly a sequence of residue classes whose class '
                                               'modulo $I^nM$ agrees with every later approximation. This is the defining '
                                               'inverse-limit condition.',
                                   'title': 'Inverse-limit description proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: The kernel of the natural map $M\\to\\widehat M$ is $\\bigcap_{n\\ge1}I^nM$.',
                                   'solution': 'An element maps to zero in the inverse limit exactly when it is zero in every '
                                               'quotient $M/I^nM$, equivalently when it lies in every $I^nM$.',
                                   'title': 'Completion map kernel proof'},
                                  {'hint': 'Start from the theorem hypotheses and identify the decisive algebraic construction.',
                                   'prompt': 'Prove: The $(x)$-adic completion of $k[x]$ is canonically $k[[x]]$.',
                                   'solution': 'A compatible sequence modulo $x^n$ uniquely specifies all coefficients of a formal '
                                               'power series, and truncating a power series gives a compatible residue system.',
                                   'title': 'Power-series completion proof'},
                                  {'hint': 'Apply the first theorem to obtain its structural description, then verify the second '
                                           "theorem's hypotheses.",
                                   'prompt': 'Prove a corollary that genuinely uses both Inverse-limit description and Completion map '
                                             'kernel.',
                                   'solution': 'A correct proof explicitly invokes both results, verifies the common hypotheses, and '
                                               'derives a new consequence rather than merely restating either theorem.',
                                   'title': 'Structural synthesis'}],
                        'standard': [{'hint': 'Use inverse limits, powers of ideals, and adic topology.',
                                      'prompt': 'Compute $\\mathbb Z/(5^3)$.',
                                      'solution': 'It is $\\mathbb Z/125\\mathbb Z$.',
                                      'title': 'Adic quotient'},
                                     {'hint': 'Use inverse limits, powers of ideals, and adic topology.',
                                      'prompt': 'Describe $k[x]/(x^4)$.',
                                      'solution': 'Every class has a representative $a_0+a_1x+a_2x^2+a_3x^3$.',
                                      'title': 'Polynomial truncation'},
                                     {'hint': 'Use inverse limits, powers of ideals, and adic topology.',
                                      'prompt': 'What is the $(x)$-adic completion of $k[x]_{(x)}$?',
                                      'solution': '$k[[x]]$.',
                                      'title': 'Completion model'},
                                     {'hint': 'Use inverse limits, powers of ideals, and adic topology.',
                                      'prompt': 'What is the transition map $A/I^{n+1}\\to A/I^n$?',
                                      'solution': 'Natural reduction modulo $I^n$.',
                                      'title': 'Inverse map'},
                                     {'hint': 'Use inverse limits, powers of ideals, and adic topology.',
                                      'prompt': 'Compute $\\bigcap_n(x^n)$ in $k[x]$.',
                                      'solution': 'It is zero.',
                                      'title': 'Intersection'}],
                        'test': [{'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: Adic completion is a direct limit of $A/I^n$.',
                                  'solution': 'False: it is an inverse limit.',
                                  'title': 'Direct limit'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: $k[x]$ is already complete in the $(x)$-adic topology.',
                                  'solution': 'False; the completion adds infinite formal power series.',
                                  'title': 'Polynomial equality'},
                                 {'hint': 'Use the smallest concrete ring, module, or resolution that can decide the claim.',
                                  'prompt': 'Test the claim: Every $I$-adic topology is automatically separated without hypotheses.',
                                  'solution': 'False; separatedness requires the intersection of powers to vanish.',
                                  'title': 'Separated automatic'}]}}}
