SPECS = {'V/01': {'apps': [('Congruence model',
                    'Explain quotient rings as arithmetic modulo $n$.',
                    'Equality of cosets is exactly congruence because differences lie in $(n)$.'),
                   ('Coordinate restriction',
                    'Interpret $k[x,y]/(y)$.',
                    'It is the coordinate ring obtained by imposing the equation $y=0$.')],
          'calc': [('Integer generated ideal', 'Find $(18,30)$ in $\\mathbb Z$.', '$(18,30)=(6)$.'),
                   ('Residue quotient', 'How many classes are in $\\mathbb Z/(15)$?', 'There are $15$ classes.'),
                   ('Polynomial reduction', 'Reduce $x^4+2x+3$ modulo $(x^2)$.', 'The class is $2x+3$.'),
                   ('Kernel', 'Find the kernel of $\\mathbb Z\\to\\mathbb Z/7\\mathbb Z$.', 'The kernel is $7\\mathbb Z$.'),
                   ('Generated ideal', 'Describe $(x,2)$ in $\\mathbb Z[x]$.', 'It consists of $xf(x)+2g(x)$.')],
          'examples': [(2,
                        'Quotient arithmetic',
                        'In $R=\\mathbb Z/12\\mathbb Z$, the ideal $(4)$ is $\\{0,4,8\\}$. The reduction map $R\\to\\mathbb '
                        'Z/4\\mathbb Z$ is surjective with kernel $(4)$, so $R/(4)\\cong\\mathbb Z/4\\mathbb Z$.'),
                       (5,
                        'Polynomial quotient',
                        'In $k[x,y]/(x,y^2)$ every class has a unique representative $a+by$. The class of $y$ is nonzero but '
                        'satisfies $y^2=0$, so the quotient exhibits a nilpotent direction explicitly.'),
                       (7,
                        'Evaluation kernel',
                        'Evaluation at $1$ gives $\\varphi:k[x]\\to k$. Polynomial division shows $\\ker\\varphi=(x-1)$, and '
                        'constants show surjectivity. Hence $k[x]/(x-1)\\cong k$.')],
          'focus': 'kernels, generated ideals, and quotient universal properties',
          'tests': [('Union test', '$2\\mathbb Z\\cup3\\mathbb Z$ is an ideal.', 'False: $2$ and $3$ belong but $5$ does not.'),
                    ('Principal ideal test', 'Every ideal of $k[x,y]$ is principal.', 'False: $(x,y)$ is not principal.'),
                    ('Field quotient test', '$\\mathbb Z/6\\mathbb Z$ is a field.', 'False: $2\\cdot3=0$ modulo $6$.')]},
 'V/02': {'apps': [('Affine point', 'Interpret $(x-a,y-b)$ geometrically.', 'It records evaluation at the affine point $(a,b)$.'),
                   ('Irreducible component',
                    'Explain why prime ideals model irreducible algebraic pieces.',
                    'The quotient domain has no nontrivial product equal to zero.')],
          'calc': [('Prime integer ideal',
                    'Decide whether $(7)$ is prime in $\\mathbb Z$.',
                    'Yes, because $\\mathbb Z/7\\mathbb Z$ is a domain.'),
                   ('Maximal integer ideal',
                    'Decide whether $(7)$ is maximal in $\\mathbb Z$.',
                    'Yes, because the quotient is a field.'),
                   ('Polynomial maximal ideal',
                    'Decide whether $(x-2)$ is maximal in $\\mathbb Q[x]$.',
                    'Yes, the quotient is $\\mathbb Q$.'),
                   ('Prime failure',
                    'Decide whether $(xy)$ is prime in $k[x,y]$.',
                    'No: the classes of $x$ and $y$ are nonzero zero divisors.'),
                   ('Prime chain', 'Give a prime chain in $k[x,y]$.', '$(0)\\subset(x)\\subset(x,y)$.')],
          'examples': [(2,
                        'Prime but not maximal',
                        'The zero ideal in $\\mathbb Z$ is prime because $\\mathbb Z$ is a domain, but it is not maximal since '
                        '$(0)\\subsetneq(2)\\subsetneq\\mathbb Z$.'),
                       (5,
                        'Maximal evaluation ideal',
                        'In $k[x,y]$, evaluation at $(a,b)$ has kernel $(x-a,y-b)$ and image $k$. The quotient is a field, so '
                        'the kernel is maximal and therefore prime.'),
                       (7,
                        'Nonprime integer ideal',
                        'The ideal $(6)$ is not prime because $2\\cdot3\\in(6)$ while neither factor belongs to $(6)$. '
                        'Equivalently, $\\mathbb Z/6\\mathbb Z$ is not a domain.')],
          'focus': 'prime and maximal quotient criteria',
          'tests': [('Prime maximality', 'Every prime ideal is maximal.', 'False: $(x)$ is prime but not maximal in $k[x,y]$.'),
                    ('Zero prime', 'The zero ideal is prime in every ring.', 'False: it is prime exactly in domains.'),
                    ('Preimage maximality',
                     'The inverse image of a maximal ideal is always maximal.',
                     'False without surjectivity; use $\\mathbb Z\\hookrightarrow\\mathbb Q$.')]},
 'V/03': {'apps': [('Reduced structure', 'Explain $R/\\sqrt{(0)}$.', 'It removes exactly nilpotent elements.'),
                   ('Zero sets',
                    'Why does replacing $I$ by $\\sqrt I$ preserve common zeros?',
                    'An element and every positive power have the same zero set.')],
          'calc': [('Integer radical', 'Compute $\\sqrt{(72)}$ in $\\mathbb Z$.', 'The radical is $(6)$.'),
                   ('Nilpotency index', 'Find the nilpotency index of $x$ in $k[x]/(x^4)$.', 'It is $4$.'),
                   ('Reduced quotient', 'Reduce $k[x]/(x^5)$.', 'The reduced quotient is $k$.'),
                   ('Radical membership', 'Is $xy\\in\\sqrt{(x^2y^2)}$?', 'Yes, because $(xy)^2=x^2y^2$.'),
                   ('Product nilradical', 'Find the nilradical of $k\\times k[t]/(t^2)$.', 'It is $0\\times(t)$.')],
          'examples': [(2,
                        'Radical of an integer ideal',
                        'For $I=(12)\\subset\\mathbb Z$, an integer has a power in $I$ exactly when it is divisible by both $2$ '
                        'and $3$. Thus $\\sqrt{(12)}=(6)$.'),
                       (5,
                        'Nilpotent quotient',
                        'In $k[x]/(x^3)$ the class of $x$ is nonzero and nilpotent. The nilradical is $(x)$ and the reduced '
                        'quotient is $k$.'),
                       (7,
                        'Monomial radical',
                        'For $I=(x^2,y^3)\\subset k[x,y]$, both $x$ and $y$ lie in $\\sqrt I$, and a polynomial with nonzero '
                        'constant term cannot have a power in $I$. Hence $\\sqrt I=(x,y)$.')],
          'focus': 'radicals, nilpotents, and reduced quotients',
          'tests': [('Radical ideal', '$(x^2)$ is radical in $k[x]$.', 'False because $x^2$ lies in the ideal but $x$ does not.'),
                    ('Reduced domain', 'Every reduced ring is a domain.', 'False: $k\\times k$ is reduced with zero divisors.'),
                    ('Zero divisor nilpotent',
                     'Every zero divisor is nilpotent.',
                     'False: $(1,0)$ in $k\\times k$ is idempotent.')]},
 'V/04': {'apps': [('Parallel arithmetic',
                    'Why can CRT split modular arithmetic into components?',
                    'The product-ring isomorphism makes operations componentwise.'),
                   ('Interpolation',
                    'Interpret CRT for distinct linear polynomial factors.',
                    'It prescribes independent values at distinct points.')],
          'calc': [('Two congruences', 'Solve $x\\equiv1\\pmod4$ and $x\\equiv2\\pmod3$.', '$x\\equiv5\\pmod{12}$.'),
                   ('CRT decomposition',
                    'Decompose $\\mathbb Z/35\\mathbb Z$.',
                    '$\\mathbb Z/35\\cong\\mathbb Z/5\\times\\mathbb Z/7$.'),
                   ('Comaximality', 'Are $(x)$ and $(x-2)$ comaximal when $2$ is invertible?', 'Yes.'),
                   ('Intersection', 'Compute $(3)\\cap(5)$ in $\\mathbb Z$.', 'It is $(15)$.'),
                   ('Idempotent', 'Find the class mod $15$ corresponding to $(1,0)$ mod $(3,5)$.', 'The class $10$.')],
          'examples': [(2,
                        'Integer CRT',
                        'The congruences $x\\equiv2\\pmod3$ and $x\\equiv4\\pmod5$ have the unique solution '
                        '$x\\equiv14\\pmod{15}$. This is the concrete form of $\\mathbb Z/15\\cong\\mathbb Z/3\\times\\mathbb '
                        'Z/5$.'),
                       (5,
                        'Orthogonal idempotents',
                        'In $\\mathbb Z/12\\cong\\mathbb Z/3\\times\\mathbb Z/4$, the classes $4$ and $9$ correspond to $(1,0)$ '
                        'and $(0,1)$. They are orthogonal idempotents and sum to $1$.'),
                       (7,
                        'Polynomial CRT',
                        'Since $(x)+(x-1)=k[x]$, one has $k[x]/(x(x-1))\\cong k\\times k$. A polynomial class is determined by '
                        'its values at $0$ and $1$.')],
          'focus': 'comaximal ideals and Chinese remainder decompositions',
          'tests': [('Noncomaximal CRT',
                     '$\\mathbb Z/8\\cong\\mathbb Z/4\\times\\mathbb Z/2$.',
                     'False: the ideals are not comaximal.'),
                    ('Intersection product', '$I\\cap J=IJ$ for all ideals.', 'False: take $I=J=(2)$ in $\\mathbb Z$.'),
                    ('Repeated factors',
                     'CRT works unchanged with repeated equal proper ideals.',
                     'False: the diagonal map is not surjective.')]},
 'V/05': {'apps': [('Denominator design',
                    'What does choosing $S$ control?',
                    'It specifies exactly which elements are forced to become units.'),
                   ('Local study',
                    'Why use $S=R\\setminus P$?',
                    'It focuses algebra at $P$ by inverting everything outside it.')],
          'calc': [('Closure', 'Is the set of nonzero integers multiplicatively closed?', 'Yes.'),
                   ('Generated system', 'List $1,6,6^2,6^3$.', '$1,6,36,216$.'),
                   ('Prime complement', 'Is $\\mathbb Z\\setminus(5)$ multiplicatively closed?', 'Yes.'),
                   ('Zero denominator', 'What if $0\\in S$?', 'The localization is the zero ring.'),
                   ('Meeting ideal', 'If $I\\cap S\\ne\\varnothing$, compute $S^{-1}I$.', 'It is $S^{-1}R$.')],
          'examples': [(2,
                        'Powers of two',
                        'The set $S=\\{1,2,4,8,\\ldots\\}$ is multiplicatively closed. Inverting it produces $\\mathbb Z[1/2]$, '
                        'where $2$ is a unit but $3$ need not be.'),
                       (5,
                        'Prime complement',
                        'If $P$ is prime, then $R\\setminus P$ is multiplicatively closed. Otherwise two elements outside $P$ '
                        'could multiply into $P$, contradicting primality.'),
                       (7,
                        'Denominator saturation',
                        'For $S=\\{1,x,x^2,\\ldots\\}\\subset k[x,y]$, every ideal meeting $S$ becomes the unit ideal after '
                        'localization, while ideals disjoint from $S$ can survive.')],
          'focus': 'multiplicative systems and denominator control',
          'tests': [('Ideal complement',
                     'The complement of every proper ideal is multiplicatively closed.',
                     'False; the ideal must be prime.'),
                    ('Nonunits',
                     'The set of nonunits is always a multiplicative system.',
                     'Not as a general structural replacement for prime complements; local-ring behavior is special.'),
                    ('Prime visibility',
                     'A prime meeting $S$ survives as a proper prime after localization.',
                     'False: it extends to the whole localized ring.')]},
 'V/06': {'apps': [('Principal open', 'Interpret $R_f$ geometrically.', 'It describes the region where $f$ is nonzero.'),
                   ('Arithmetic near $p$', 'Why use $\\mathbb Z_{(p)}$?', 'All integers prime to $p$ become units.')],
          'calc': [('Unit', 'Is $2$ a unit in $\\mathbb Z[1/2]$?', 'Yes, inverse $1/2$.'),
                   ('Localized ideal', 'Compute $(2)\\mathbb Z[1/2]$.', 'It is the whole ring.'),
                   ('Prime denominators',
                    'Describe denominators in $\\mathbb Z_{(7)}$.',
                    'They are integers not divisible by $7$.'),
                   ('Polynomial inverse', 'Find the inverse of $x^3$ in $k[x,y]_x$.', 'It is $x^{-3}$.'),
                   ('Zero fraction', 'When is $a/s=0$?', 'When some denominator $u\\in S$ satisfies $ua=0$.')],
          'examples': [(2,
                        'Integer localization',
                        'Localizing $\\mathbb Z$ at powers of $6$ gives $\\mathbb Z[1/6]$. Fractions with denominators dividing '
                        'powers of $6$ occur, while $1/5$ does not.'),
                       (5,
                        'Principal localization',
                        'In $k[x,y]_x$, $x$ is a unit, so $(x,y)$ becomes the whole ring. The ideal $(y)$ remains proper and '
                        'records the part visible where $x$ is invertible.'),
                       (7,
                        'Prime localization',
                        'The ring $\\mathbb Z_{(5)}$ consists of $a/b$ with $5\\nmid b$. Its unique maximal ideal consists of '
                        'fractions whose numerator is divisible by $5$.')],
          'focus': 'fraction localization and its universal property',
          'tests': [('Injectivity', '$R\\to S^{-1}R$ is always injective.', 'False: denominator torsion can map to zero.'),
                    ('Prime extension', 'Every prime extends to a proper prime.', 'False if the prime meets $S$.'),
                    ('Collapse', 'A nonzero ring can never localize to zero.', 'False if $0$ is inverted.')]},
 'V/07': {'apps': [('Local checking',
                    'Why check modules at all prime localizations?',
                    'A module is zero exactly when all prime localizations vanish.'),
                   ('Restriction',
                    'Interpret $M_f$.',
                    'It is module data restricted to the principal open where $f$ is invertible.')],
          'calc': [('Zero module', 'Compute $S^{-1}0$.', 'It is zero.'),
                   ('Killed quotient', 'Compute $(R/(x))_x$.', 'It is zero.'),
                   ('Free module', 'Compute $S^{-1}(R^3)$.', 'It is $(S^{-1}R)^3$.'),
                   ('Element vanishing', 'When does $m/1$ vanish?', 'When some $s\\in S$ annihilates $m$.'),
                   ('Quotient localization', 'Identify $S^{-1}(M/N)$.', 'It is $S^{-1}M/S^{-1}N$.')],
          'examples': [(2,
                        'Localized torsion',
                        'Localizing $\\mathbb Z/12$ at powers of $2$ kills the $4$-primary part and leaves the $3$-primary '
                        'information. This is a concrete instance of denominators annihilating torsion.'),
                       (5,
                        'Module vanishing',
                        'For $M=R/(f)$, localization at powers of $f$ gives $M_f=0$: the relation $f\\cdot1=0$ and invertibility '
                        'of $f$ force $1=0$.'),
                       (7,
                        'Exact sequence localization',
                        'Localizing $0\\to\\mathbb Z\\xrightarrow{\\cdot2}\\mathbb Z\\to\\mathbb Z/2\\to0$ at powers of $2$ '
                        'turns the first map into an isomorphism and the localized cokernel into zero.')],
          'focus': 'localization of modules and exactness',
          'tests': [('Nonzero preservation', 'Localization preserves every nonzero module.', 'False: $(R/(f))_f=0$.'),
                    ('Module injectivity', '$M\\to S^{-1}M$ is always injective.', 'False when $M$ has $S$-torsion.'),
                    ('New support', 'Localization can create support at primes meeting $S$.', 'False; those primes disappear.')]},
 'V/08': {'apps': [('Near one prime',
                    'Why are local rings adapted to local algebra?',
                    'They invert everything away from one chosen prime.'),
                   ('Residue measurement',
                    'What does the residue field measure?',
                    'It records scalars at the chosen local point.')],
          'calc': [('Unit test', 'Is $3/7$ a unit in $\\mathbb Z_{(5)}$?', 'Yes.'),
                   ('Nonunit test', 'Is $10/3$ a unit in $\\mathbb Z_{(5)}$?', 'No.'),
                   ('Maximal ideal', 'Find the maximal ideal of $k[x]_{(x)}$.', 'It is $(x)k[x]_{(x)}$.'),
                   ('Residue field', 'Find the residue field of $\\mathbb Z_{(p)}$.', 'It is $\\mathbb F_p$.'),
                   ('Polynomial residue', 'Find $k[x,y]_{(x,y)}/(x,y)$.', 'It is $k$.')],
          'examples': [(2,
                        'Integers at a prime',
                        'In $\\mathbb Z_{(5)}$, $a/b$ is a unit exactly when $5\\nmid a$. The fractions with numerator divisible '
                        'by $5$ form the unique maximal ideal.'),
                       (5,
                        'Polynomial local ring',
                        'The ring $k[x]_{(x)}$ consists of $f/g$ with $g(0)\\ne0$. Its maximal ideal is generated by $x$, and a '
                        'fraction is a unit exactly when its residue at $x=0$ is nonzero.'),
                       (7,
                        'Two-variable local ring',
                        'In $k[x,y]_{(x,y)}$, every polynomial with nonzero constant term becomes a unit. The maximal ideal is '
                        'generated by the images of $x$ and $y$.')],
          'focus': 'local rings, maximal ideals, and unit criteria',
          'tests': [('Two maximals', 'A ring with two distinct maximal ideals is local.', 'False.'),
                    ('Prime spectrum', 'A local ring has no nonmaximal prime ideals.', 'False.'),
                    ('Unit residue', 'An element in the maximal ideal can be a unit.', 'False in a local ring.')]},
 'V/09': {'apps': [('Presentations',
                    'How do exact sequences encode generators and relations?',
                    'A free surjection supplies generators and its kernel records relations.'),
                   ('Failure measures',
                    'What do kernel and cokernel measure?',
                    'They measure failure of injectivity and surjectivity.')],
          'calc': [('Kernel', 'Find the kernel of multiplication by $4$ on $\\mathbb Z$.', 'It is zero.'),
                   ('Cokernel', 'Find its cokernel.', 'It is $\\mathbb Z/4$.'),
                   ('Injection', 'Is multiplication by $2$ on $\\mathbb Z$ injective?', 'Yes.'),
                   ('Matrix rank', 'Find the rank of the projection $k^3\\to k^2$.', 'The rank is $2$.'),
                   ('Section', 'Give a section of $A\\oplus B\\to B$.', '$b\\mapsto(0,b)$.')],
          'examples': [(2,
                        'Kernel and cokernel',
                        'Multiplication by $6$ gives a short exact sequence $0\\to\\mathbb Z\\to\\mathbb Z\\to\\mathbb '
                        'Z/6\\to0$. The kernel is zero and the cokernel is the residue module.'),
                       (5,
                        'Matrix exactness',
                        'The inclusion $k^2\\to k^3$ into the first two coordinates has cokernel $k$. Projection onto the third '
                        'coordinate completes a short exact sequence.'),
                       (7,
                        'Split sequence',
                        'The sequence $0\\to A\\to A\\oplus B\\to B\\to0$ splits via $b\\mapsto(0,b)$, exhibiting the middle '
                        'module as a direct sum.')],
          'focus': 'kernels, cokernels, and exact sequences',
          'tests': [('Injective surjective',
                     'Every injective module map is surjective.',
                     'False: multiplication by $2$ on $\\mathbb Z$.'),
                    ('Surjective injective', 'Every surjection is injective.', 'False: $\\mathbb Z\\to\\mathbb Z/2$.'),
                    ('Zero composite',
                     '$g\\circ f=0$ implies exactness at the middle term.',
                     'False: it gives only image contained in kernel.')]},
 'V/10': {'apps': [('Scalar extension',
                    'Why is $B\\otimes_AM$ extension of scalars?',
                    'It is universal for reinterpreting the $A$-action through $B$.'),
                   ('Affine products',
                    'Why do tensor products of algebras model product coordinates?',
                    'They combine independent coordinate functions over the base field.')],
          'calc': [('Unit tensor', 'Compute $R\\otimes_RM$.', 'It is $M$.'),
                   ('Zero tensor', 'Compute $M\\otimes_R0$.', 'It is zero.'),
                   ('Cyclic tensor', 'Compute $\\mathbb Z/4\\otimes\\mathbb Z/6$.', 'It is $\\mathbb Z/2$.'),
                   ('Coprime tensor', 'Compute $\\mathbb Z/4\\otimes\\mathbb Z/9$.', 'It is zero.'),
                   ('Quotient tensor', 'Compute $(R/I)\\otimes_R(R/J)$.', 'It is $R/(I+J)$.')],
          'examples': [(2,
                        'Cyclic tensor product',
                        'For positive integers $m,n$, $\\mathbb Z/m\\otimes\\mathbb Z/n\\cong\\mathbb Z/\\gcd(m,n)$. Thus '
                        '$\\mathbb Z/6\\otimes\\mathbb Z/15\\cong\\mathbb Z/3$.'),
                       (5,
                        'Tensor with a quotient',
                        'For an ideal $I$ and module $M$, $(R/I)\\otimes_RM\\cong M/IM$. Tensor relations force elements of $I$ '
                        'to act as zero.'),
                       (7,
                        'Extension of scalars',
                        'For a field extension $K/k$, $K\\otimes_k k^n\\cong K^n$. A $k$-basis becomes a $K$-basis after scalar '
                        'extension.')],
          'focus': 'tensor products and their universal property',
          'tests': [('Left exactness',
                     'Tensoring always preserves injections.',
                     'False: tensor multiplication by $2$ with $\\mathbb Z/2$.'),
                    ('Pure tensor',
                     'A pure tensor is zero only if one factor is zero.',
                     'False: use $\\mathbb Z/2\\otimes\\mathbb Z/3=0$.'),
                    ('Dimension rule',
                     'Dimension multiplication holds for arbitrary modules.',
                     'False; it is a vector-space formula under suitable finiteness.')]},
 'V/11': {'apps': [('Solving equations',
                    'Why extend the coefficient field?',
                    'It can reveal roots and factorizations while retaining canonical base-change data.'),
                   ('Fiber module', 'Interpret $M\\otimes_A\\kappa(P)$.', 'It is the fiber of $M$ at the prime $P$.')],
          'calc': [('Quotient base change', 'Compute $B\\otimes_AA/I$.', 'It is $B/IB$.'),
                   ('Polynomial extension', 'Compute $K\\otimes_kk[x]$.', 'It is $K[x]$.'),
                   ('Free module', 'Compute $B\\otimes_AA^n$.', 'It is $B^n$.'),
                   ('Nested quotient', 'Compute $(A/I)/(J/I)$.', 'It is $A/J$.'),
                   ('Module quotient', 'Compute $(A/I)\\otimes_AM$.', 'It is $M/IM$.')],
          'examples': [(2,
                        'Base change of a quotient',
                        'For $A\\to B$ and $I\\subset A$, one has $B\\otimes_AA/I\\cong B/IB$. Equations defining $I$ are '
                        'transported to the new coefficient ring.'),
                       (5,
                        'Field extension splitting',
                        'Base changing $\\mathbb R[x]/(x^2+1)$ to $\\mathbb C$ gives $\\mathbb C[x]/((x-i)(x+i))$. A polynomial '
                        'irreducible over the original field can split after base change.'),
                       (7,
                        'Flat base change',
                        'For $0\\to N\\to M\\to M/N\\to0$, tensoring with a flat $A$-algebra $B$ preserves the injection and '
                        'gives a short exact base-changed sequence.')],
          'focus': 'quotients and base change',
          'tests': [('Injectivity', 'Every base change preserves injections.', 'False without flatness.'),
                    ('Irreducibility',
                     'Irreducible polynomials remain irreducible after every field extension.',
                     'False: $x^2+1$ from $\\mathbb R$ to $\\mathbb C$.'),
                    ('Extension contraction',
                     'Ideal extension and contraction are always inverse.',
                     'False for arbitrary ring maps.')]},
 'V/12': {'apps': [('Linear equations',
                    'How does a presentation matrix encode a module?',
                    'Generators are free coordinates and matrix columns or rows encode relations.'),
                   ('Stable base change',
                    'Why are finitely presented modules convenient under base change?',
                    'The same finite relation matrix can be transported coefficientwise.')],
          'calc': [('Hom from ring', 'Compute $\\operatorname{Hom}_R(R,M)$.', 'It is $M$.'),
                   ('Hom to zero', 'Compute $\\operatorname{Hom}_R(M,0)$.', 'It is zero.'),
                   ('Cyclic Hom',
                    'Compute $\\operatorname{Hom}_{\\mathbb Z}(\\mathbb Z/6,\\mathbb Z/15)$.',
                    'It is isomorphic to $\\mathbb Z/3$.'),
                   ('Cokernel', 'Find the cokernel of multiplication by $f$ on $R$.', 'It is $R/(f)$.'),
                   ('Presentation', 'Present $R/(f,g)$ using finite free modules.', 'Use $R^2\\to R\\to R/(f,g)\\to0$.')],
          'examples': [(2,
                        'Hom from a cyclic module',
                        'A map $\\mathbb Z/n\\to M$ is determined by the image of $1$, which must be killed by $n$. Hence '
                        '$\\operatorname{Hom}_{\\mathbb Z}(\\mathbb Z/n,M)\\cong M[n]$.'),
                       (5,
                        'Presentation matrix',
                        'The cokernel of $\\operatorname{diag}(x,y):R^2\\to R^2$ is $R/(x)\\oplus R/(y)$. The diagonal matrix '
                        'records two independent relations.'),
                       (7,
                        'Hom and localization',
                        'For finitely presented $M$, localization commutes with Hom in the first variable: the finite '
                        'presentation reduces the claim to kernels between finite powers.')],
          'focus': 'Hom and finite presentations',
          'tests': [('Finite generation',
                     'Every finitely generated module is finitely presented over every ring.',
                     'False over non-Noetherian rings.'),
                    ('Hom exactness',
                     '$\\operatorname{Hom}(M,-)$ is always right exact.',
                     'False unless $M$ has extra projectivity.'),
                    ('Hom localization',
                     'Localization commutes with Hom for every first module.',
                     'False in general; finite presentation is a standard sufficient hypothesis.')]},
 'V/13': {'apps': [('Vector bundles',
                    'Why do finite projectives model algebraic vector bundles?',
                    'They are locally free of finite rank.'),
                   ('Resolutions',
                    'Why are projectives useful in resolutions?',
                    'Surjections onto them split, eliminating lifting obstructions.')],
          'calc': [('Free projective', 'Is $R^5$ projective?', 'Yes.'),
                   ('Direct summand', 'If $R^4=P\\oplus Q$, is $P$ projective?', 'Yes.'),
                   ('Idempotent complement', 'What complements $eR$ when $e^2=e$?', '$(1-e)R$.'),
                   ('Localized free', 'Compute $(R^n)_P$.', 'It is $R_P^n$.'),
                   ('Split quotient', 'What does a section of $F\\to P$ imply?', 'It makes $P$ a direct summand of $F$.')],
          'examples': [(2,
                        'Idempotent projective',
                        'If $e^2=e$, then $R=eR\\oplus(1-e)R$. Thus $eR$ is a direct summand of the free module $R$ and is '
                        'projective.'),
                       (5,
                        'Splitting criterion',
                        'A module $P$ is projective exactly when every surjection onto $P$ splits. Applying this to a free '
                        'surjection shows that projectives are precisely direct summands of free modules.'),
                       (7,
                        'Local freeness',
                        'A finitely generated projective module becomes free after localization at a prime. Its local rank is '
                        'the algebraic analogue of vector-bundle rank.')],
          'focus': 'free modules, projective splittings, and idempotents',
          'tests': [('Projective free',
                     'Every projective module is free.',
                     'False over general rings; idempotent summands give examples.'),
                    ('Submodule free', 'Every submodule of a free module is projective over every ring.', 'False in general.'),
                    ('Finite generation',
                     'Every projective module is finitely generated.',
                     'False: infinite-rank free modules are projective.')]},
 'V/14': {'apps': [('Families',
                    'Why is flatness associated with well-behaved families?',
                    'It prevents new kernel relations from appearing under base change.'),
                   ('Local test', 'Why can flatness be checked locally?', 'Flatness is local on the base ring.')],
          'calc': [('Free flat', 'Is $R^n$ flat?', 'Yes.'),
                   ('Localization flat', 'Is $R_f$ flat over $R$?', 'Yes.'),
                   ('Injection preservation', 'What must a flat tensor functor do to injections?', 'It must preserve them.'),
                   ('Integer quotient', 'Is $\\mathbb Z/3$ flat over $\\mathbb Z$?', 'No.'),
                   ('Direct sum', 'Is a direct sum of flat modules flat?', 'Yes.')],
          'examples': [(2,
                        'Localization is flat',
                        'For every multiplicative set $S$, $S^{-1}R$ is flat because $S^{-1}R\\otimes_RM\\cong S^{-1}M$ and '
                        'localization is exact.'),
                       (5,
                        'Nonflat cyclic module',
                        'Tensor $\\mathbb Z\\xrightarrow{\\cdot2}\\mathbb Z$ with $\\mathbb Z/2$. The induced map is zero, so '
                        'injectivity is lost and $\\mathbb Z/2$ is not flat.'),
                       (7,
                        'Ideal criterion',
                        'Flatness can be tested by requiring $I\\otimes_RM\\to M$ to be injective for finitely generated ideals '
                        '$I$. This turns exactness into a relation test.')],
          'focus': 'flatness and exactness under tensor product',
          'tests': [('Flat projective',
                     'Every flat module is projective.',
                     'False: $\\mathbb Q$ is flat but not projective over $\\mathbb Z$.'),
                    ('Torsion-free', 'Torsion-free is equivalent to flat over every domain.', 'False in general.'),
                    ('Tensor exact',
                     'Tensoring with any module is exact.',
                     'False: tensor is always right exact, not always left exact.')]}}
