#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv,json,re
from pathlib import Path

GOALS = {'V/01': ['verify that a subset is an ideal and compute ideals generated by explicit elements;',
          'construct quotient rings and identify their elements and operations concretely;',
          'compute kernels and images of ring homomorphisms and apply the first isomorphism theorem;',
          'translate ideal containment in a quotient through the correspondence theorem;',
          'compute sums and intersections of ideals in elementary rings;',
          'distinguish ring, subring, ideal, and quotient constructions by examples and counterexamples;'],
 'V/02': ['test whether an ideal is prime or maximal using quotient-domain and quotient-field criteria;',
          'compute prime and maximal ideals in standard rings such as integers, polynomial rings, and products;',
          'prove that maximal ideals are prime and identify hypotheses needed for converses;',
          'analyze inverse images of prime ideals under ring homomorphisms;',
          'distinguish irreducible elements from prime ideals and prime elements in examples;',
          'construct chains of prime ideals that reveal basic dimension-theoretic behavior;'],
 'V/03': ['compute radicals of explicit ideals and the nilradical of standard quotient rings;',
          'prove that the nilradical is the intersection of all prime ideals;',
          'test whether an ideal is radical by analyzing powers or quotient nilpotents;',
          'identify nilpotent elements in quotient rings from defining relations;',
          'relate radical containment to vanishing of powers of ideals or elements;',
          'construct examples separating prime, primary-looking, radical, and nonradical ideals;'],
 'V/04': ['verify comaximality of ideals and apply the Chinese remainder theorem;',
          'construct explicit isomorphisms between quotient rings and products of quotients;',
          'solve simultaneous congruences by lifting idempotents or Bezout relations;',
          'extend the two-ideal theorem to finite pairwise-comaximal families;',
          'compute kernels of diagonal quotient maps and identify intersections of ideals;',
          'distinguish direct-product decompositions that arise from comaximal ideals from unrelated product presentations;'],
 'V/05': ['verify that a subset is multiplicatively closed and determine when it contains zero;',
          'construct saturation sets and identify elements annihilated after localization;',
          'compare localization at powers of one element with localization at a general multiplicative system;',
          'identify universal properties satisfied by maps inverting a prescribed multiplicative set;',
          'compute equality conditions between fractions using the localization equivalence relation;',
          'choose multiplicative systems adapted to primes, elements, or geometric open sets;'],
 'V/06': ['construct localized rings and simplify explicit fractions;',
          'apply the universal property of localization to extend ring homomorphisms uniquely;',
          'compute prime ideals of a localization from primes disjoint from the multiplicative set;',
          'determine when an element becomes zero or a unit after localization;',
          'compare localization at a prime, maximal ideal, and single element;',
          'prove that localization commutes with quotients in the standard compatible form;'],
 'V/07': ['construct localized modules and simplify fractions of module elements;',
          'determine when a localized module element vanishes;',
          'prove that localization is an exact functor on modules;',
          'compute localized kernels, images, quotients, and finite presentations;',
          'test module identities locally at prime ideals and recover global consequences where valid;',
          'distinguish module localization from tensoring with an unrelated algebra by using the canonical isomorphism with localized rings;'],
 'V/08': ['verify that a ring is local and identify its unique maximal ideal;',
          'compute localizations at prime ideals and describe their units and maximal ideals;',
          'prove the unit criterion that elements outside the maximal ideal are invertible in a local ring;',
          'use Nakayama-type reasoning in elementary finitely generated module situations where available;',
          'translate global ideal questions into local questions at primes;',
          'construct examples of local rings arising from polynomial, quotient, and localization constructions;'],
 'V/09': ['verify exactness of sequences by computing kernels and images at each term;',
          'construct short exact sequences from submodules and quotients;',
          'apply the snake-lemma-style kernel/cokernel viewpoint in elementary diagrams where developed;',
          'identify splitting maps and determine when a short exact sequence splits;',
          'compute kernels, cokernels, images, and coimages of module homomorphisms;',
          'distinguish left exact, right exact, and exact behavior of basic module functors;'],
 'V/10': ['construct tensor products from bilinear maps using their universal property;',
          'compute elementary tensor products of cyclic modules and quotients;',
          'use tensor relations to simplify pure tensors and detect zero tensors;',
          'prove right exactness of tensor product and identify where injectivity may fail;',
          'apply base-change identities involving tensor products of algebras and modules;',
          'distinguish tensor product from direct product, direct sum, and ordinary multiplication;'],
 'V/11': ['compute tensor products after quotienting rings or modules;',
          'derive standard base-change isomorphisms from universal properties;',
          'compare extension and restriction of scalars along a ring homomorphism;',
          'track ideals and modules through quotient and base-change constructions;',
          'identify when tensoring preserves or destroys injectivity in quotient sequences;',
          'use localization as a special case of base change to simplify calculations;'],
 'V/12': ['compute Hom modules for finitely generated free and cyclic modules;',
          'distinguish finitely generated from finitely presented modules by explicit presentations;',
          "use finite presentation to justify commuting Hom with filtered colimits or localization in the chapter's setting;",
          'construct presentation matrices for modules and interpret generators and relations;',
          'apply the Hom universal property and naturality in concrete calculations;',
          'identify which finiteness hypothesis is needed in a proposed Hom/base-change statement;'],
 'V/13': ['recognize free modules from explicit bases and coordinate decompositions;',
          'test projectivity using lifting properties, direct summands, or idempotent matrices;',
          'prove that free modules are projective and that direct summands of projective modules are projective;',
          'construct projective modules from idempotents and splitting exact sequences;',
          'distinguish projective modules from free modules by examples where available;',
          'localize projective modules and analyze finite projectivity through local criteria;'],
 'V/14': ['test flatness using preservation of injective maps or exact sequences under tensor product;',
          'prove that free and projective modules are flat;',
          'verify that localization is flat as a module over the original ring;',
          'use ideal criteria for flatness in finitely generated situations where developed;',
          'construct examples of nonflat modules from torsion or failed injectivity after tensoring;',
          'distinguish flatness from projectivity and freeness by structural consequences and examples;'],
 'V/15': ['verify Noetherianity using ascending chains or finite generation of ideals/submodules;',
          'apply Hilbert basis-type arguments to polynomial extensions where established;',
          'prove that submodules and quotients of finitely generated modules over Noetherian rings retain finiteness;',
          'construct stabilization arguments from ascending chains;',
          'compute finite generating sets extracted from chain conditions;',
          'distinguish Noetherian hypotheses from merely finitely generated individual ideals or modules;'],
 'V/16': ['compute the support of a module from localizations at prime ideals;',
          "identify support as the set of primes containing the annihilator for finitely generated modules under the chapter's hypotheses;",
          'compute supports of quotients, direct sums, and localized modules;',
          'relate support to vanishing of a module after localization;',
          'prove basic closedness properties of support for finitely generated modules;',
          'use support to detect where module-theoretic phenomena are nontrivial;'],
 'V/17': ['identify associated primes from annihilators of module elements;',
          'compute associated primes in basic quotient and primary-type examples;',
          'prove that associated primes lie inside the support;',
          'use zero divisors on a module to detect unions of associated primes under Noetherian hypotheses;',
          'analyze behavior of associated primes under localization;',
          'distinguish minimal primes of support from embedded associated primes in representative examples;'],
 'V/18': ['construct inverse systems of quotients defining I-adic completion;',
          'compute elementary completions such as power-series or p-adic-type examples;',
          'verify separatedness by analyzing intersections of powers of an ideal;',
          'compare a module with its completion through the canonical map;',
          'use completeness to solve compatible systems of congruences;',
          'distinguish completion from localization and from ordinary product constructions;'],
 'V/19': ['test whether an element is integral over a subring by finding a monic polynomial relation;',
          'prove closure of integral elements under addition and multiplication using finite-module criteria;',
          'apply the determinant trick or finite-generation criterion for integral dependence;',
          'analyze integral extensions under quotients and localization;',
          'show how integrality constrains prime ideals through lying-over-type statements developed in the chapter;',
          'distinguish integral dependence from algebraic dependence or arbitrary polynomial relations;'],
 'V/20': ['compute integral closures in elementary domains and fraction fields;',
          'verify that a domain is integrally closed using monic-equation criteria;',
          'construct normalization maps from a domain to its integral closure;',
          'analyze normalization under localization in standard finite-type examples;',
          'identify singular algebraic presentations that become simpler after normalization;',
          'distinguish normality of a domain from reducedness, factoriality, or smoothness;'],
 'V/21': ['verify the valuation-ring criterion that for each fraction either it or its inverse lies in the ring;',
          'construct valuation rings from valuations on fraction fields;',
          'identify prime ideals and units in elementary valuation rings;',
          'compare divisibility of principal ideals through the valuation ordering;',
          'use valuation rings to test integral closure in fraction fields where the chapter establishes the criterion;',
          'distinguish discrete valuation rings from general valuation rings by value-group behavior;'],
 'V/22': ['verify that a sequence of modules and differentials forms a chain complex by checking consecutive composites vanish;',
          'compute cycles, boundaries, and homology groups in explicit finite complexes;',
          'construct chain maps and verify compatibility with differentials;',
          'identify exact complexes by vanishing homology;',
          'compute mapping behavior induced on homology by chain maps;',
          'distinguish chain complexes, exact sequences, and graded modules by their additional differential structure;'],
 'V/23': ['construct free resolutions of elementary modules from generators and relations;',
          'verify exactness of a proposed resolution at each stage;',
          'compare two free resolutions through chain maps lifting the identity;',
          'use resolutions to compute invariants that are independent of the chosen resolution;',
          'truncate or extend resolutions while preserving exactness where justified;',
          'distinguish a presentation from a full resolution by identifying higher syzygies;'],
 'V/24': ['compute first syzygies as relations among a chosen generating set;',
          'construct higher syzygies recursively from kernels in a free resolution;',
          'translate presentation matrices into syzygy modules;',
          'analyze how changing generators changes a presentation but not the underlying module;',
          'use syzygies to continue a free resolution;',
          'distinguish minimal relations from redundant generators or redundant syzygies;'],
 'V/25': ["identify minimal free resolutions over local or graded rings using the chapter's minimality criterion;",
          'compute Betti numbers from ranks of modules in a minimal resolution;',
          'detect and remove contractible or unit-entry summands from nonminimal resolutions;',
          'compare minimal resolutions up to isomorphism in settings where uniqueness holds;',
          'use residue-field tensoring to read off minimal generators or Betti numbers;',
          'distinguish homological length, projective dimension, and resolution length;'],
 'V/26': ['compute Tor groups from a projective or free resolution and tensor product;',
          'verify that \\(\\operatorname{Tor}_0\\) recovers ordinary tensor product;',
          'use long exact Tor sequences arising from short exact sequences;',
          'detect nonflatness through nonvanishing \\(\\operatorname{Tor}_1\\);',
          'compute Tor for cyclic modules and quotient rings in elementary examples;',
          'track functoriality and independence of the chosen resolution;'],
 'V/27': ['compute Ext groups from projective resolutions and Hom complexes;',
          'verify that \\(\\operatorname{Ext}^0\\) recovers ordinary Hom;',
          'use long exact Ext sequences and connecting morphisms in concrete examples;',
          'interpret \\(\\operatorname{Ext}^1\\) in terms of extensions where developed;',
          'compute Ext for cyclic modules or quotients from short free resolutions;',
          'distinguish variance in the first and second arguments and track induced maps correctly;'],
 'V/28': ['identify which failure of exactness a derived functor is measuring;',
          'construct left derived functors from projective or flat resolutions and right derived functors from injective resolutions;',
          'explain Tor as derived tensor and Ext as derived Hom;',
          'derive long exact sequences from short exact sequences of complexes or resolved objects;',
          'compare different resolutions using chain-homotopy and universality principles;',
          'connect derived-functor computations to later geometric uses such as sheaf cohomology and intersection theory;']}
METHODS = {'V/01': ['Check closure under subtraction and multiplication by arbitrary ring elements; both are needed for an ideal, not merely a subring.',
          'To identify an ideal generated by elements, write a general finite ring-linear combination of those generators.',
          'For sums and intersections, prove both containments against the universal smallest/largest ideal descriptions.',
          'In a quotient, two representatives are equal exactly when their difference lies in the ideal; use that before computing operations.',
          'Compute the kernel first when applying an isomorphism theorem; the quotient by that kernel is the canonical source of injectivity.',
          'For a ring map, distinguish image as a subring from kernel as an ideal before invoking quotient structure.',
          'Lift an ideal of A/I to its inverse image in A and check that it contains I; quotienting back should recover the original ideal.',
          'Use polynomial, integer-residue, or product-ring examples to test whether an asserted ideal or quotient statement really holds.'],
 'V/02': ['Use A/p being a domain as the fastest prime-ideal test when the quotient is easy to understand.',
          'Use A/m being a field as the fastest maximal-ideal test; then compare with the prime criterion.',
          'In Z, reduce prime and maximal ideal questions to the generator n and factorization of n.',
          'In a polynomial ring over a field, identify when a principal quotient is a domain or field from irreducibility of the polynomial.',
          'For inverse images, compose the quotient map with the homomorphism and use that preimages of prime ideals are prime when the target '
          'quotient is a domain.',
          'To show maximal implies prime, use the field structure of the quotient rather than a direct ideal argument.',
          'For a product ring, inspect coordinate idempotents; prime ideals must kill exactly one factor in the basic finite-product case.',
          'To build a prime chain, choose nested ideals whose quotient domains are transparent rather than guessing from element factorization '
          'alone.'],
 'V/03': ['An element lies in sqrt(I) exactly when some positive power lies in I; test powers before searching for generators of the radical.',
          'Compute the nilradical as sqrt((0)); in a quotient, nilpotents come from elements whose powers land in the defining ideal.',
          'To prove the nilradical is contained in every prime, place \\(x^n\\) in the prime and use primality repeatedly to force x into it.',
          'For the reverse containment, use a prime ideal avoiding a nonnilpotent element; this is the nontrivial direction of the intersection '
          'theorem.',
          'An ideal I is radical exactly when A/I has no nonzero nilpotents; pass to the quotient when possible.',
          'For principal monomial ideals, compare exponents: the radical keeps the underlying prime factors and forgets multiplicities.',
          'Check whether cancellation or quotient relations create nilpotents before classifying a ring as reduced.',
          "Separate 'radical ideal' from 'prime ideal': every prime is radical, but intersections of distinct primes supply standard nonprime "
          'radical examples.'],
 'V/04': ['Prove comaximality by finding a+b=1 with a in I and b in J; this identity drives the explicit CRT decomposition.',
          'The kernel of A -> A/I x A/J is I intersect J; compute it before invoking the first isomorphism theorem.',
          'When I+J=A, prove I intersect J=IJ by inserting 1=a+b into an arbitrary element of the intersection.',
          'To construct a simultaneous solution, build idempotent-like coefficients from a Bezout relation and combine the prescribed residues.',
          'For finitely many ideals, verify pairwise comaximality and use induction rather than assuming the two-ideal proof automatically scales.',
          'In Z, translate comaximality to gcd(m,n)=1 before solving congruences.',
          'Check surjectivity of the product quotient map by lifting one coordinate at a time with the CRT coefficients.',
          'Do not replace intersections by products without comaximality; test a simple counterexample such as powers of one prime ideal.'],
 'V/05': ['Verify 1 lies in S and that products stay in S; if 0 lies in S, the localization collapses to the zero ring.',
          'To compare fractions, use the actual equivalence relation: some s in S must annihilate the cross-multiplication difference.',
          'An element a/1 becomes zero exactly when some s in S annihilates a; look for that witness.',
          'For localization at powers of f, rewrite every denominator as \\(f^n\\) and keep track of which powers are allowed.',
          'To use the universal property, first check the target map sends every element of S to a unit.',
          'Saturation records elements that become invertible after localization; test by multiplying into S.',
          'For a prime p, use \\(S=A\\setminus p\\) so precisely the elements outside p become units.',
          'Choose S from the algebraic goal: powers of one element for D(f), complement of a prime for local behavior, or a larger system for '
          'simultaneous inversion.'],
 'V/06': ['Simplify a/s by multiplying numerator and denominator only by elements allowed by the localization equivalence.',
          'To prove a map from \\(S^{-1}A\\) exists, define \\(a/s\\mapsto \\varphi(a)\\varphi(s)^{-1}\\) and check it is independent of '
          'representatives.',
          'A prime of \\(S^{-1}A\\) contracts to a prime of A disjoint from S; extend a disjoint prime and check the two operations are inverse.',
          'To see whether a/1 is a unit, ask whether some multiple of a lies in S.',
          'For localization at p, every element outside p is a unit and \\(pA_p\\) is the unique maximal ideal.',
          'Use \\(S^{-1}(A/I)\\cong S^{-1}A/S^{-1}I\\) only after checking the image of S does not force the quotient to collapse unexpectedly.',
          'Localization at f can be computed as adjoining an inverse with relation ft=1; use this presentation when explicit algebra helps.',
          'Check equality locally by cross multiplication with an S-witness rather than cancelling denominators as if the ring were a domain.'],
 'V/07': ['Represent module fractions as m/s and use the same denominator-equivalence idea as for rings, with annihilation by an element of S.',
          'm/1 is zero in \\(S^{-1}M\\) exactly when some s in S satisfies sm=0; this is the basic local-vanishing test.',
          'To prove exactness after localization, clear denominators and use exactness before localization to find the needed preimage.',
          'Use \\(S^{-1}M\\cong S^{-1}A\\otimes_A M\\) when tensor-product tools simplify the argument.',
          'For a quotient, localize the short exact sequence \\(0\\to N\\to M\\to M/N\\to0\\) and read off \\(S^{-1}(M/N)\\).',
          'To test an equality of submodules locally, compare their localizations at every prime and then invoke the local-global criterion only '
          'when its hypotheses apply.',
          'Finite presentations localize by localizing the presentation matrix entrywise.',
          'Do not infer that local vanishing at one prime gives global vanishing; determine which primes must be checked.'],
 'V/08': ['In a local ring, show every element outside the maximal ideal is a unit by using maximality of the principal ideal it generates together '
          'with the maximal ideal.',
          'To identify the maximal ideal of \\(A_p\\), localize p itself and show every fraction outside \\(pA_p\\) is invertible.',
          'A ring is local iff the nonunits form an ideal; test this criterion when the maximal ideal is not obvious.',
          'For a quotient of a local ring, track the image of the maximal ideal and check when it remains the unique maximal ideal.',
          'Localizing at a maximal ideal produces a local ring; describe its residue field as \\(A_m/mA_m\\).',
          'Use Nakayama only for finitely generated modules and a Jacobson-radical/maximal-ideal hypothesis; identify that hypothesis explicitly.',
          'To prove a finitely generated module is zero from M=mM, reduce generators modulo m and apply Nakayama.',
          'Translate a global statement to \\(A_p\\) or \\(M_p\\), prove it at each relevant prime, then use a local-global criterion rather than '
          'assuming local truth glues automatically.'],
 'V/09': ['At each term of a sequence, compute image of the incoming map and kernel of the outgoing map; exactness means equality of those '
          'submodules.',
          'For 0 -> N -> M -> Q -> 0, verify injectivity, surjectivity, and that Q is the quotient M/N up to the induced isomorphism.',
          'A splitting of the surjection gives \\(M\\cong N\\oplus Q\\); construct the isomorphism explicitly from inclusion and section.',
          'A splitting of the inclusion gives a retraction; use its kernel as the complementary summand.',
          'Compute cokernel as target modulo image, not merely as a set-theoretic complement.',
          'To test functor exactness, apply the functor to a short exact sequence and inspect where injectivity or surjectivity is lost.',
          'For diagram arguments, chase one element at a time through commuting squares and write down where exactness is used.',
          'Do not confuse exactness of a complex with splitting; a short exact sequence can be nonsplit.'],
 'V/10': ['Use the universal property: a bilinear map M x N -> P factors uniquely through M tensor N.',
          "Apply relations (m+m') tensor n, m tensor (n+n'), and (am) tensor n = m tensor (an) to simplify tensors.",
          'For cyclic modules, start from \\(A/I\\otimes_A N\\cong N/IN\\) and reduce the computation to a quotient.',
          'To prove right exactness, tensor a presentation and identify the resulting cokernel.',
          'Injectivity can fail after tensoring; look for torsion killed by multiplication before and after tensoring.',
          'Use pure tensors only as generators; not every tensor is itself pure.',
          'For base change, reassociate tensors carefully and keep track of which ring acts at each stage.',
          'Distinguish direct sum from tensor product by their universal properties: one is additive coproduct, the other linearizes bilinear maps.'],
 'V/11': ['Use \\((A/I)\\otimes_A M\\cong M/IM\\) as the basic quotient/base-change identity.',
          'For ring maps \\(A\\to B\\to C\\), reassociate \\(C\\otimes_B(B\\otimes_A M)\\) to \\(C\\otimes_A M\\).',
          'Extension of scalars sends \\(M\\) to \\(B\\otimes_A M\\); restriction of scalars forgets the B-action but keeps the underlying abelian '
          'group/module.',
          'When tensoring a quotient sequence, expect right exactness and check separately whether the left injection survives.',
          'Local base change is just \\(B=S^{-1}A\\); translate general tensor identities to localization to test them.',
          'Track the image of an ideal under extension carefully: IB is generated by images of elements of I, not an arbitrary set-theoretic image.',
          'For quotient then base change, compare \\(B\\otimes_A A/I\\) with \\(B/IB\\).',
          'Use universal properties to construct the natural map first, then prove it is an isomorphism rather than guessing the formula.'],
 'V/12': ['For a free module \\(A^n\\), identify \\(\\operatorname{Hom}_A(A^n,N)\\) with \\(N^n\\) by recording images of basis vectors.',
          'For A/I, a homomorphism A/I -> N is determined by an element annihilated by I; translate Hom into an annihilator condition.',
          'A finite presentation \\(A^m\\to A^n\\to M\\to0\\) lets you compute Hom(M,N) as a kernel after applying Hom.',
          'Finite generation controls generators; finite presentation also finitely controls relations; keep these two finiteness levels separate.',
          'To see why finite presentation matters for localization or filtered-colimit statements, inspect where infinitely many relations would '
          'prevent a finite denominator choice.',
          'Construct the presentation matrix from the chosen generators and relation vectors column by column.',
          'Hom is contravariant in the first variable and covariant in the second; track arrow directions before composing induced maps.',
          'Use the universal property of a cokernel/presentation to prove a proposed Hom description is natural.'],
 'V/13': ['A free basis gives a direct coordinate isomorphism with \\(A^n\\); verify both spanning and uniqueness of coordinates.',
          'Projectivity means lifting maps across surjections; draw the lifting square and identify the map that must exist.',
          'To show a direct summand is projective, combine a lifting for the ambient projective module with the projection onto the summand.',
          'A splitting of 0 -> K -> F -> P -> 0 exhibits P as a direct summand of a free module.',
          'An idempotent matrix \\(e\\) with \\(e^2=e\\) gives the projective module im(e); use \\(A^n=\\operatorname{im}(e)\\oplus\\ker(e)\\).',
          'Localizing a direct-summand decomposition proves localization of a projective module is projective.',
          'For finitely generated projectives, test local freeness at primes only in settings where the local criterion has been established.',
          'Do not assume projective implies free globally; search for nontrivial idempotents or geometric examples when the ring is not '
          'local/PID-like.'],
 'V/14': ["To test flatness, tensor an injective map N' -> N with M and check whether injectivity survives.",
          'Free modules are flat because tensoring with \\(A^I\\) gives direct sums of the original sequence.',
          'Projective modules are flat because direct summands of flat modules remain flat.',
          'Localization is flat because localized exact sequences remain exact; connect the two viewpoints explicitly.',
          "Use the ideal criterion by testing I tensor M -> M for finitely generated ideals only when the theorem's hypotheses permit it.",
          'For a nonflat quotient A/I, tensor a short exact sequence involving multiplication by an element and look for a new kernel.',
          '\\(\\operatorname{Tor}_1\\) detects failure of flatness once Tor is available: nonzero \\(\\operatorname{Tor}_1\\) is an obstruction.',
          'Separate flat from projective: flatness preserves finite equations/exactness, while projectivity is a lifting/direct-summand condition.'],
 'V/15': ['To prove Noetherianity from ACC, start an ascending chain of ideals and show its union is finitely generated, forcing stabilization.',
          'To prove ACC from finite generation, take the union ideal of a chain and place its finitely many generators in one stage.',
          'Submodules of finitely generated modules over a Noetherian ring are finitely generated; this is the key closure property to use.',
          'Quotients of finitely generated modules are generated by images of any finite generating set.',
          'For polynomial extensions, isolate leading coefficients and use induction/Hilbert basis reasoning rather than assuming finite generation '
          'termwise.',
          'To extract generators from a chain, adjoin one new element whenever possible; Noetherianity says this process must stop.',
          'Check whether the ring is Noetherian before inferring every submodule of a finite module is finitely generated.',
          "Distinguish 'this ideal is finitely generated' from 'every ideal is finitely generated'; only the latter characterizes a Noetherian "
          'ring.'],
 'V/16': ['By definition p lies in \\(\\operatorname{Supp}(M)\\) exactly when \\(M_p\\) is nonzero; localize before drawing geometric conclusions.',
          'For finitely generated M, use Supp(M)=V(Ann M); prove both directions with a finite set of generators.',
          'Supp(A/I)=V(I); reduce quotient examples to prime containment.',
          'Support of a direct sum is the union of supports; localize the direct sum and test nonvanishing componentwise.',
          'Localization restricts support to primes compatible with the multiplicative set; identify the corresponding prime set explicitly.',
          'To prove support is closed for finite M, compute the annihilator and use the Zariski-closed set it defines.',
          'If \\(M_p=0\\) for every prime p, use finite generation/local-global reasoning when needed to conclude M=0.',
          'Do not confuse support with associated primes: associated primes are selected annihilator primes inside the generally larger support.'],
 'V/17': ['p is associated to M when p=Ann(m) for some element m; search for elements with prime annihilator.',
          'For A/I, annihilators of residue classes can expose associated primes more directly than primary decomposition.',
          'Every associated prime lies in the support because localizing the witnessing element at its annihilator prime keeps it nonzero.',
          'Under Noetherian hypotheses, zero divisors on M are detected by associated primes; identify the element killed by a zero divisor.',
          'Localize the witnessing equation Ann(m)=p to relate associated primes of M to those of \\(M_p\\).',
          'Minimal primes of Supp(M) are associated in standard Noetherian settings; distinguish them from possible embedded primes.',
          'For direct sums, compare annihilators of pairs and use known associated-prime union formulas where established.',
          'Check the Noetherian/finite hypotheses before invoking finiteness of the associated-prime set.'],
 'V/18': ['Write the completion as \\(\\varprojlim A/I^n\\) or \\(\\varprojlim M/I^nM\\) and keep the transition maps explicit.',
          'A compatible sequence of residue classes must agree modulo every lower power; verify this before declaring it a point of the inverse '
          'limit.',
          'For k[x] completed at (x), identify coefficients successively modulo \\(x^n\\) to recover a formal power series.',
          'Separatedness asks whether the intersection of all \\(I^nM\\) is zero; test an element lying in every power.',
          'The canonical map sends m to its compatible residue classes; its kernel is exactly the I-adic intersection.',
          'Completeness means every compatible congruence system comes from an element; formulate the reconstruction one stage at a time.',
          'Do not confuse product of quotients with inverse limit: compatibility conditions cut out a proper subset of the product.',
          'Compare localization and completion carefully; one inverts elements while the other records increasingly fine congruence data.'],
 'V/19': ['Integral means satisfying a monic polynomial over A; monicity is essential, so do not use an arbitrary algebraic relation.',
          'To prove closure under addition/multiplication, place the elements inside a common finite A-module algebra and use the finite-module '
          'criterion.',
          'The determinant trick starts from a finite module stable under multiplication by x and produces a monic characteristic relation.',
          'Integrality descends to quotients by reducing the monic polynomial modulo the ideal.',
          'Integrality localizes because the same monic relation survives after localizing coefficients.',
          'For prime behavior, extend/contraction arguments use integrality together with the lying-over mechanism; identify the exact theorem '
          'before applying it.',
          'Every element of a finite A-algebra is integral over A; use Cayley--Hamilton on multiplication by that element.',
          "Separate 'algebraic over the fraction field' from 'integral over A': denominators in a polynomial relation matter."],
 'V/20': ['To compute integral closure, start with fractions x and test whether a monic equation over A can hold.',
          'An integrally closed domain contains every fraction integral over it; phrase the test inside the fraction field.',
          'Normalization is the inclusion A -> Abar in the fraction field or total ring used by the chapter; identify that ambient field first.',
          'Localization of an integrally closed domain remains integrally closed; clear denominators in a monic relation after localization.',
          'For a singular subring such as \\(k[t^2,t^3]\\), test whether t is integral and adjoin it to reach the normalization.',
          'Normal does not mean UFD automatically; keep integrally closed and factorial conditions distinct.',
          'Reducedness only excludes nilpotents; it does not imply integral closure in the fraction field.',
          'Check finite-generation hypotheses before asserting normalization is finite as an A-module.'],
 'V/21': ['For each nonzero fraction x in K, test whether \\(x\\) or \\(x^{-1}\\) lies in \\(V\\); this total divisibility criterion characterizes '
          'valuation rings.',
          'From a valuation \\(v:K^*\\to\\Gamma\\), define \\(V=\\{x:v(x)\\ge0\\}\\cup\\{0\\}\\) and verify closure under ring operations.',
          'Units are exactly elements of valuation zero; positive valuation elements form the maximal ideal in the standard valuation-domain '
          'construction.',
          'Principal ideals are ordered by reverse valuation: larger value means smaller principal ideal.',
          'A discrete valuation ring has value group isomorphic to Z and a uniformizer of least positive value; identify that element.',
          'To show valuation rings are integrally closed, compare valuations in a monic integral equation and derive a contradiction for negative '
          'valuation.',
          'Prime ideals correspond to convex/order data in the value group in general; do not force the DVR picture onto every valuation ring.',
          'Use valuation-overring criteria for integral closure only after fixing the common fraction field.'],
 'V/22': ['Check \\(d_n d_{n+1}=0\\) at every degree before calling the sequence a chain complex.',
          'Cycles are \\(\\ker d_n\\) and boundaries are \\(\\operatorname{im}d_{n+1}\\); homology is \\(Z_n/B_n\\).',
          'To prove exactness at degree n, show every cycle is already a boundary.',
          'A chain map f satisfies d f = f d degreewise; write the commuting square at the degree in question.',
          'An induced homology map is well-defined because chain maps send cycles to cycles and boundaries to boundaries.',
          'For a short complex, compute kernels and images explicitly rather than using homological terminology as a substitute for calculation.',
          'Degree shifts and sign conventions matter when comparing chain and cochain complexes; state the convention first.',
          'Zero homology at every degree means exactness, but an exact complex need not be split or contractible.'],
 'V/23': ['Start from a surjection \\(F_0\\to M\\) from a free module on chosen generators; the first syzygy is its kernel.',
          'Choose a free module \\(F_1\\) surjecting onto that kernel, then repeat recursively to build a free resolution.',
          'At each degree, exactness requires image of the new differential to equal the previous kernel.',
          'A presentation stops after \\(F_1\\to F_0\\to M\\); a resolution continues by resolving the relation modules.',
          'Comparison maps between resolutions are built inductively using projectivity of the free modules.',
          'Different resolutions may look different, so only use invariants proved independent up to chain homotopy.',
          'Truncating a resolution changes exactness at the cut unless the remaining kernel is projective/free as required.',
          'For explicit modules, derive the first differential from a presentation matrix before inventing higher maps.'],
 'V/24': ['Given generators of M, place them in a surjection \\(F_0\\to M\\); the kernel consists exactly of the first syzygies.',
          'Write each relation as a coordinate vector in \\(F_0\\); those vectors generate the syzygy module.',
          'To compute higher syzygies, repeat the kernel computation for the map from a free module onto the previous syzygy module.',
          'A presentation matrix encodes relations in its columns or rows according to convention; fix that convention before computing kernels.',
          'Changing generators changes the presentation matrix by free-module operations but not the isomorphism class of M.',
          'Remove a redundant relation only after proving it lies in the submodule generated by the others.',
          'Syzygies are the data needed for the next differential in a free resolution; verify consecutive maps compose to zero.',
          'In graded settings, track degrees of generators and relations so the syzygy maps are homogeneous.'],
 'V/25': ['Over a local ring, minimality is detected by differential matrices having entries in the maximal ideal; check this degree by degree.',
          'Over a graded ring, use positive-degree entries in the irrelevant maximal ideal for the analogous minimality test.',
          'Tensor a minimal resolution with the residue field; all differentials vanish, so the graded vector-space dimensions reveal Betti numbers.',
          'If a differential matrix contains a unit entry, split off the corresponding contractible free summand to reduce the resolution.',
          'Minimal resolutions are unique up to isomorphism in the standard local/graded setting; compare ranks degree by degree.',
          'Projective dimension is the least possible resolution length by projectives, not simply the length of an arbitrary resolution.',
          'Betti numbers are ranks in a minimal resolution; nonminimal resolutions can inflate them artificially.',
          'Check finite-generation/local hypotheses before using minimal-resolution uniqueness or residue-field criteria.'],
 'V/26': ['Choose a free/projective resolution \\(P_\\bullet\\to M\\), tensor it with N, then compute homology of the resulting complex.',
          'Degree zero homology is \\(\\operatorname{coker}(P_1\\otimes N\\to P_0\\otimes N)\\), naturally \\(M\\otimes N\\).',
          'For cyclic quotients, use a short resolution by multiplication and compute kernel/cokernel after tensoring.',
          'A short exact sequence in one variable gives a long exact Tor sequence; write the neighboring terms before solving for the unknown group.',
          'Nonzero \\(\\operatorname{Tor}_1\\) records failure of tensoring to preserve injectivity; compare with the flatness criterion.',
          'Projective modules have vanishing higher Tor because they admit a resolution concentrated in degree zero.',
          'Independence of resolution comes from comparison maps unique up to homotopy; do not compare chain groups literally.',
          'Track which argument is fixed and how ring/module structures act before writing Tor over A.'],
 'V/27': ['Choose a projective resolution \\(P_\\bullet\\to M\\) and apply \\(\\operatorname{Hom}_A(P_\\bullet,N)\\); Ext is the cohomology of that '
          'cochain complex.',
          'Degree zero cohomology recovers \\(\\operatorname{Hom}_A(M,N)\\); verify this from the first two terms of the resolution.',
          'For a cyclic quotient, apply Hom to a short free resolution and compute kernel/cokernel of multiplication.',
          'A short exact sequence yields a long exact Ext sequence; mark variance so arrows go in the correct direction.',
          "\\(\\operatorname{Ext}^1\\) classifies extensions in the chapter's setting; identify the split extension as the zero class.",
          'Projective first arguments have vanishing higher Ext when computed projectively.',
          'Changing the second argument is covariant while changing the first is contravariant; write induced maps before composing them.',
          'Independence of the chosen resolution is a homotopy-invariance statement, not equality of the resulting cochain complexes.'],
 'V/28': ['First identify whether the original functor is left exact or right exact; that determines whether right or left derived functors are '
          'needed.',
          'For a right exact functor, resolve by projectives/flats and take homology after applying the functor.',
          'For a left exact functor, use injective resolutions or an equivalent acyclic class and take cohomology.',
          '\\(\\operatorname{Tor}_n\\) is obtained by deriving tensor product; check degree zero recovers ordinary tensor before interpreting higher '
          'degrees.',
          '\\(\\operatorname{Ext}^n\\) is obtained by deriving Hom; track whether the projective resolution is in the contravariant first variable '
          'or an injective resolution in the second.',
          'Long exact sequences come from short exact sequences of complexes and the connecting homomorphism in homology/cohomology.',
          'To compare resolutions, use comparison maps and chain homotopies; invariance is not a statement that the resolutions are identical.',
          'The derived-category viewpoint localizes quasi-isomorphisms, turning resolution-dependent constructions into ordinary functorial objects '
          'up to the intended equivalence.']}

TRIAD=re.compile(
    r"(?P<exercise_block>\\begin\{exercise\}\\label\{exr:v(?P<ch>\d{2})-(?P<idx>\d{2})\}(?P<exercise>.*?)\\end\{exercise\}\s*)"
    r"(?P<hint_block>\\begin\{hint\}(?P<hint>.*?)\\end\{hint\}\s*)"
    r"(?P<solution_block>\\begin\{solution\}(?P<solution>.*?)\\end\{solution\})",
    re.S,
)

def validate_payload():
    bad=[]
    for family,data in (("GOALS",GOALS),("METHODS",METHODS)):
        for code,arr in data.items():
            for idx,s in enumerate(arr,1):
                nonascii=sorted({c for c in s if ord(c)>127})
                outside=re.sub(r"\\\(.*?\\\)","",s)
                raw=sorted({c for c in "^_\\#$%&" if c in outside})
                if nonascii or raw:
                    bad.append({"family":family,"chapter":code,"index":idx,
                                "nonascii":nonascii,"raw_text_mode_tex":raw,"text":s})
    if bad:
        raise RuntimeError("Unsafe pedagogy payload: "+json.dumps(bad,ensure_ascii=False))

def read_status(repo):
    with (repo/"editorial/CHAPTER_STATUS.tsv").open("r",encoding="utf-8-sig",newline="") as f:
        return list(csv.DictReader(f,delimiter="\t"))

def paths(repo):
    out={}
    for r in read_status(repo):
        c=(r.get("chapter_code") or "").strip()
        if c in GOALS:
            if r.get("status")!="FROZEN" or r.get("next_action")!="COMPLETE":
                raise RuntimeError(f"{c}: expected FROZEN/COMPLETE")
            out[c]=repo/r["canonical_path"]
    missing=sorted(set(GOALS)-set(out))
    if missing: raise RuntimeError(f"missing Volume V status rows: {missing}")
    return out

def replace_goals(text,code):
    block=[r"\section*{Learning goals}","After this chapter, the reader should be able to:",r"\begin{itemize}"]
    block += [rf"\item {x}" for x in GOALS[code]]
    block += [r"\end{itemize}",""]
    rep="\n".join(block)
    rx=re.compile(r"\\section\*\{Learning goals\}.*?(?=\\section\*\{Conceptual roadmap\})",re.S)
    if not rx.search(text): raise RuntimeError(f"{code}: goals block missing")
    return rx.sub(lambda _:rep,text,count=1)

def replace_hints(text,code):
    n=0; ch=int(code.split("/")[1])
    def repl(m):
        nonlocal n
        if int(m.group("ch"))!=ch:return m.group(0)
        idx=int(m.group("idx")); n+=1
        return m.group("exercise_block")+"\\begin{hint}\n"+METHODS[code][idx-1]+"\n\\end{hint}\n"+m.group("solution_block")
    return TRIAD.sub(repl,text),n

def main():
    validate_payload()
    ap=argparse.ArgumentParser()
    ap.add_argument("--repo",required=True)
    ap.add_argument("--mode",choices=("goals","hints","all"),required=True)
    ap.add_argument("--start",type=int,default=1)
    ap.add_argument("--end",type=int,default=28)
    a=ap.parse_args(); repo=Path(a.repo).resolve(); pp=paths(repo)
    summary=[]
    for i in range(a.start,a.end+1):
        code=f"V/{i:02d}"; p=pp[code]; text=p.read_text(encoding="utf-8-sig"); before=text; h=0
        if a.mode in ("goals","all"): text=replace_goals(text,code)
        if a.mode in ("hints","all"):
            text,h=replace_hints(text,code)
            if h!=8: raise RuntimeError(f"{code}: expected 8 hints, replaced {h}")
        if text!=before: p.write_text(text.rstrip()+"\n",encoding="utf-8")
        summary.append({"chapter_code":code,"changed":text!=before,"hints_replaced":h})
    print(json.dumps(summary,indent=2,ensure_ascii=False))
    return 0
if __name__=="__main__": raise SystemExit(main())
