#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

GOALS = {'III/01': ['verify that a proposed family of sets is a sigma-algebra and identify which closure axiom fails when it is not;',
            'construct the sigma-algebra generated by elementary families and relate it to Borel sets in concrete spaces;',
            'derive monotonicity and countable subadditivity from countable additivity;',
            'apply continuity from below and continuity from above with the correct finiteness hypothesis;',
            'distinguish finite, sigma-finite, complete, and incomplete measure spaces by examples;',
            'construct null-set and completion examples showing why measurable structure matters beyond pointwise set inclusion;'],
 'III/02': ['verify measurability of a function from inverse images of Borel sets or from level-set criteria;',
            'prove that algebraic combinations and pointwise limits of measurable functions are measurable under the stated hypotheses;',
            'construct simple-function approximations to nonnegative measurable functions;',
            'compute measurable level sets for explicit functions and use them to analyze distribution functions;',
            'distinguish almost-everywhere equality from pointwise equality in measure-theoretic arguments;',
            'produce examples of nonmeasurable behavior by identifying where the measurable-structure hypotheses fail;'],
 'III/03': ['compute Lebesgue integrals first for simple functions and then for nonnegative or integrable functions;',
            'use monotone approximation by simple functions to justify integral identities;',
            'separate positive and negative parts and determine when a signed function is integrable;',
            'apply basic comparison and linearity properties of the integral with all finiteness assumptions checked;',
            'compare Lebesgue and Riemann integrals on functions covered by both theories;',
            'construct examples of measurable functions with finite, infinite, or undefined signed integrals;'],
 'III/04': ['apply monotone, Fatou, and dominated convergence theorems after verifying their distinct hypotheses;',
            'construct dominating functions suitable for dominated-convergence arguments;',
            "use Fatou's lemma to obtain one-sided integral inequalities from pointwise limits;",
            'distinguish pointwise, almost-everywhere, and norm convergence in examples where the conclusions differ;',
            'build counterexamples showing why domination or monotonicity cannot simply be omitted;',
            'choose the weakest convergence theorem that actually applies to a given sequence of measurable functions;'],
 'III/05': ['construct product sigma-algebras and product measures in standard sigma-finite settings;',
            "apply Tonelli's theorem to nonnegative functions and Fubini's theorem to integrable functions with the correct hypotheses;",
            'justify changing the order of integration by checking absolute integrability or nonnegativity;',
            'compute iterated integrals on rectangles and simple product domains;',
            'identify measurable sections and use them to interpret product-measure statements;',
            'construct examples where changing integration order fails because the Fubini hypotheses are not satisfied;'],
 'III/06': ['compute \\(L^p\\) norms and determine membership in \\(L^p\\) for explicit singular or decaying functions;',
            'distinguish equality almost everywhere from equality as pointwise functions in \\(L^p\\) spaces;',
            "prove completeness of \\(L^p\\) in the chapter's setting using Cauchy-sequence control;",
            'compare \\(L^p\\) spaces on finite- and infinite-measure domains with explicit inclusions or counterexamples;',
            'use truncation or simple-function approximation to construct dense subclasses;',
            'analyze limiting behavior in \\(L^p\\) without confusing norm convergence with pointwise convergence;'],
 'III/07': ["apply Hölder's inequality with correctly chosen conjugate exponents;",
            "derive Minkowski's inequality from Hölder and use it to prove the triangle inequality in \\(L^p\\);",
            'compute interpolation exponents from endpoint data in elementary interpolation inequalities;',
            'identify equality or near-equality cases in Hölder-type estimates;',
            'use Hölder and Minkowski to control products, sums, and integral operators;',
            'construct examples showing why exponent restrictions such as \\(1/p+1/q=1\\) are structural rather than cosmetic;'],
 'III/08': ["apply Egorov's theorem on finite-measure sets and track the exceptional-set measure explicitly;",
            'use Vitali-type covering ideas to obtain quantitative measure estimates;',
            'compute weak-\\(L^p\\) distribution-function bounds for explicit functions;',
            'distinguish strong \\(L^p\\) membership from weak-\\(L^p\\) membership by examples;',
            'translate decay of level-set measure into weak-norm estimates and back again;',
            'construct examples showing why finite measure, covering hypotheses, or strong-integrability assumptions cannot be dropped silently;'],
 'III/09': ['compute Fourier coefficients of elementary periodic functions using symmetry before integration;',
            'derive partial sums and identify their relation to convolution with Dirichlet-type kernels;',
            'apply convergence criteria at continuity points and jump discontinuities with the correct limiting value;',
            'use orthogonality to prove coefficient identities and energy estimates;',
            'distinguish pointwise, uniform, and \\(L^2\\) convergence of Fourier series in representative examples;',
            'construct examples illustrating slow convergence or Gibbs-type behavior near jumps;'],
 'III/10': ['compute convolutions of elementary functions and determine their support;',
            'prove basic algebraic properties of convolution under the required integrability hypotheses;',
            'use Young-type estimates to control convolution norms;',
            'show how approximate identities recover functions in the appropriate topology;',
            'distinguish smoothing by convolution from pointwise multiplication;',
            'construct mollifier-based approximations while tracking support, normalization, and convergence mode;'],
 'III/11': ["compute Fourier transforms of elementary functions under the chapter's normalization convention;",
            'derive translation, modulation, scaling, and differentiation identities from the transform definition;',
            'identify when the transform is continuous, bounded, or decaying from integrability and regularity assumptions;',
            'compute inverse transforms in examples where an inversion theorem applies;',
            'use convolution-multiplication duality to simplify transform calculations;',
            'check transform formulas by dimensional, symmetry, or inverse-transform consistency tests rather than memorization alone;'],
 'III/12': ['derive the Fourier transform of a Gaussian and track normalization constants correctly;',
            'use differentiation and multiplication identities to compute transforms of Gaussian-weighted polynomials;',
            'apply completion-of-the-square arguments in transform integrals;',
            'derive heat-kernel and semigroup formulas from Gaussian transform calculus;',
            'compare spatial and frequency widths quantitatively for Gaussian families;',
            'construct transform identities by differentiating with respect to parameters when justified;'],
 'III/13': ["apply Plancherel's theorem to convert \\(L^2\\) norm or inner-product problems into frequency-space calculations;",
            'extend the Fourier transform from an integrable dense subclass to \\(L^2\\);',
            'use Parseval identities to compute energies and orthogonality relations;',
            'distinguish \\(L^1\\)-based pointwise transform statements from \\(L^2\\)-equivalence-class statements;',
            'prove uniqueness results from vanishing Fourier transform in \\(L^2\\);',
            'solve elementary convolution or multiplier problems by exploiting the unitary \\(L^2\\) transform structure;'],
 'III/14': ['verify that a function belongs to the Schwartz space by bounding all polynomially weighted derivatives;',
            'show that differentiation, multiplication by polynomials, and Fourier transformation preserve the Schwartz space;',
            'construct seminorm estimates controlling standard Schwartz-space operations;',
            'distinguish rapid decay from compact support and from mere integrability;',
            'use density of Schwartz functions in relevant \\(L^p\\) or \\(L^2\\) settings where established;',
            'produce examples that lie in one standard function space but not another by comparing decay and smoothness requirements;'],
 'III/15': ['verify that a smooth function has compact support inside the prescribed open set;',
            'construct test functions by rescaling, translating, multiplying, and patching standard bumps;',
            'track support under multiplication, differentiation, and coordinate changes;',
            'distinguish convergence in test-function space from pointwise or uniform convergence alone;',
            'build cutoff functions equal to one on a compact set and supported in a larger open set;',
            'explain why compact support eliminates boundary terms in distributional integration by parts;'],
 'III/16': ['verify that a linear functional defines a distribution by checking continuity on test functions;',
            'embed locally integrable functions into distributions and compute their action on test functions;',
            'compute distributional derivatives by transferring derivatives to test functions with the correct sign;',
            'derive the derivative of the Heaviside function and related jump distributions;',
            'prove convergence of distributions by testing against an arbitrary fixed test function;',
            'apply smooth multiplication and differential operators to distributions without reverting to pointwise intuition;'],
 'III/17': ['determine the support of regular and singular distributions from their action on test functions;',
            'compute supports of Dirac masses, derivatives of Dirac masses, and finite linear combinations;',
            'distinguish singular support from ordinary support in representative examples;',
            'use localization by test functions to prove that a distribution vanishes on an open set;',
            'analyze how multiplication by smooth functions changes support;',
            'construct distributions concentrated on lower-dimensional or discrete sets in elementary settings;'],
 'III/18': ['verify that a distribution is tempered by establishing polynomial-growth bounds on Schwartz test functions;',
            'embed polynomially growing functions and finite measures into tempered distributions when justified;',
            'distinguish general distributions from tempered distributions by their admissible test-function spaces;',
            'apply differentiation and polynomial multiplication inside the tempered-distribution framework;',
            'construct examples of tempered singular distributions such as Dirac masses and their derivatives;',
            'identify growth behavior that prevents a distribution from being tempered;'],
 'III/19': ['define and compute Fourier transforms of tempered distributions by duality;',
            'derive transform formulas for Dirac masses, derivatives, polynomials, and exponentials in distributional form;',
            'use differentiation and multiplication identities without assuming classical integrability;',
            'solve algebraic multiplier equations in frequency space at the distribution level;',
            'check constants and signs by testing transform identities against Schwartz functions;',
            'distinguish ordinary-function Fourier formulas from their distributional extensions;'],
 'III/20': ['verify that a locally integrable function has a proposed weak derivative by testing the defining integration-by-parts identity;',
            'compute weak derivatives of piecewise smooth functions and identify jump contributions when they occur distributionally;',
            'distinguish weak differentiability from classical differentiability;',
            'prove uniqueness of weak derivatives up to almost-everywhere equality;',
            'use approximation by smooth functions to justify weak-derivative identities;',
            'construct functions with weak derivatives that fail to have classical derivatives at exceptional points;'],
 'III/21': ['compute Sobolev norms and determine membership in \\(W^{k,p}\\) or \\(H^k\\) for explicit functions;',
            'use weak derivatives to formulate Sobolev-space regularity;',
            'apply basic embedding or inequality results only after checking dimension, exponent, and domain hypotheses;',
            'interpret traces or boundary values in settings where the chapter establishes them;',
            'use completeness and Hilbert-space structure of \\(H^k\\) in variational arguments;',
            'distinguish Sobolev regularity from pointwise smoothness by examples and counterexamples;'],
 'III/22': ['construct smooth approximations by mollification and quantify the mode of convergence;',
            'prove density of smooth or compactly supported smooth functions in the function spaces covered by the chapter;',
            'control boundary effects when approximating functions on domains rather than on all of \\(\\mathbb R^n\\);',
            'use cutoff functions and convolution in the correct order to preserve desired support properties;',
            'distinguish approximation in norm from pointwise approximation;',
            'identify spaces or boundary conditions for which naive mollification does not directly give the required dense subclass;'],
 'III/23': ['derive the weak formulation of a boundary-value problem by multiplying by a test function and integrating by parts;',
            'identify the natural trial and test spaces for elementary weak PDE problems;',
            'verify boundedness and coercivity of bilinear forms in representative examples;',
            'apply an existence theorem such as Lax--Milgram only after checking its hypotheses;',
            'interpret weak boundary conditions and distinguish them from pointwise boundary equalities;',
            'recover additional regularity or classical equations from a weak solution when justified;'],
 'III/24': ['verify that a candidate fundamental solution satisfies \\(L\\Phi=\\delta\\) in the distributional sense;',
            'derive fundamental solutions from Fourier multipliers in constant-coefficient examples;',
            'compute solutions of forced equations by convolution with a fundamental solution when the operation is justified;',
            'track singularity, scaling, and dimensional dependence of standard fundamental solutions;',
            'distinguish a fundamental solution from a Green function adapted to boundary conditions;',
            'use distributional differentiation to check formulas that are singular at the source point;'],
 'III/25': ['construct Green functions from fundamental solutions plus boundary-correction terms in elementary domains;',
            'verify the defining differential equation and boundary conditions separately;',
            'derive representation formulas for solutions using Green functions;',
            'interpret symmetry and positivity properties when the operator and domain permit them;',
            'distinguish free-space kernels from domain-dependent Green functions;',
            'check jump or derivative conditions that determine one-dimensional Green functions uniquely;'],
 'III/26': ['construct Green kernels for second-order Sturm--Liouville boundary-value problems from two homogeneous solutions;',
            'compute the Wronskian and use it to normalize the kernel;',
            'verify continuity of the kernel and the prescribed derivative jump across the diagonal;',
            'check boundary conditions in each variable before accepting a proposed kernel;',
            'derive solution representations by integrating the forcing term against the kernel;',
            'distinguish regular, periodic, Dirichlet, and Neumann kernel constructions by their boundary conditions;'],
 'III/27': ['classify elementary second-order operators as elliptic by inspecting the principal symbol or coefficient matrix;',
            'apply weak or classical maximum principles only after checking ellipticity and sign hypotheses;',
            'use maximum principles to prove uniqueness of boundary-value problems;',
            'derive comparison principles from the maximum principle;',
            'construct examples showing how sign changes or degeneracy can invalidate the conclusion;',
            'connect elliptic estimates with qualitative control of interior extrema and boundary data;'],
 'III/28': ['diagonalize translation-invariant or separable PDE operators by Fourier or eigenfunction transforms;',
            'derive transformed algebraic or ordinary differential equations from PDEs;',
            'solve model heat, wave, or elliptic equations by inverse transform under the stated hypotheses;',
            'interpret spectral multipliers as frequency-dependent propagation, damping, or resolvent factors;',
            'compare Fourier-transform, Fourier-series, and eigenfunction-expansion methods according to the domain and boundary conditions;',
            'check transformed solutions by substituting back into the original PDE and verifying initial or boundary data;']}

METHODS = {'III/01': ["Check closure under complements and countable unions first; the remaining sigma-algebra operations follow from De Morgan's laws.",
            'Use the generated-sigma-algebra definition as an intersection of all sigma-algebras containing the generators.',
            'For Borel measurability on \\(\\mathbb R\\), reduce to intervals with rational endpoints rather than arbitrary open sets.',
            'Derive monotonicity by writing the larger set as a disjoint union of the smaller set and its difference.',
            'For sigma-finiteness, exhibit an explicit countable cover by measurable sets of finite measure.',
            'Disjointify the increasing sequence and apply countable additivity term by term.',
            'For continuity from above, subtract from the finite set \\(E_1\\); that is exactly where \\(\\mu(E_1)<\\infty\\) is used.',
            'To check completeness, start with a measurable null set and ask whether every one of its subsets is measurable.'],
 'III/02': ['Use the inverse-image definition: test \\(f^{-1}((a,\\infty))\\) or another generating family of Borel sets.',
            'Reduce measurability of algebraic combinations to measurability of the coordinate map on \\(\\mathbb R^2\\).',
            'For pointwise limits, express the relevant level set using countable unions and intersections of level sets of the approximating '
            'functions.',
            'Approximate a nonnegative measurable function from below by dyadic simple functions.',
            'Write the distribution function as \\(\\mu(\\{|f|>t\\})\\) and compute the level set before its measure.',
            'Almost-everywhere equality means the exceptional set has measure zero; identify that set explicitly.',
            'To prove measurability of a supremum or infimum, rewrite the level set in terms of countably many measurable level sets.',
            'For a composition, verify that the outer map is Borel measurable so inverse images remain in the sigma-algebra.'],
 'III/03': ['Start with the simple-function formula \\(\\int \\sum a_k1_{E_k}=\\sum a_k\\mu(E_k)\\) on disjoint pieces.',
            'For a nonnegative function, choose an increasing sequence of simple functions and use the defining supremum/monotone limit.',
            'Split \\(f\\) into \\(f^+-f^-\\) and check that both positive-part integrals are finite before calling \\(f\\) integrable.',
            'Use monotonicity of the integral directly when one function is bounded above by another almost everywhere.',
            'Linearity for signed functions is safest after verifying absolute integrability of all terms involved.',
            'To compare with the Riemann integral, use the common simple/step approximations rather than treating the two definitions as identical.',
            'An infinite integral is allowed for nonnegative functions; distinguish this from an undefined expression \\(\\infty-\\infty\\).',
            'For truncation, replace \\(f\\) by \\(\\min(f,n)\\) or by bounded-support cutoffs and then pass to the limit.'],
 'III/04': ['For monotone convergence, check \\(0\\le f_n\\uparrow f\\) almost everywhere before passing the limit through the integral.',
            'Fatou gives a lower bound for \\(\\int\\liminf f_n\\); write the liminf explicitly before applying it.',
            'For dominated convergence, find one integrable \\(g\\) with \\(|f_n|\\le g\\) for every \\(n\\).',
            'Do not replace domination by pointwise boundedness; the dominating function must itself be integrable.',
            'To build a counterexample, use moving spikes whose heights and supports defeat uniform integral control.',
            'If the functions change sign, apply Fatou to a nonnegative modification or use dominated convergence instead.',
            'Separate almost-everywhere convergence from convergence in measure or norm; the theorem only needs the stated mode.',
            'Choose the theorem with hypotheses you can actually verify rather than the strongest theorem you remember.'],
 'III/05': ['On rectangles, start from measurable rectangles and extend to the product sigma-algebra before using product measure.',
            'Tonelli applies to nonnegative functions even when the integral is infinite; use it before worrying about absolute integrability.',
            'Fubini requires integrability; check \\(\\int |f|<\\infty\\) before changing the integration order.',
            'Compute the inner integral as a function of the outer variable and verify its measurability.',
            'For indicator functions, reduce Fubini/Tonelli to measuring sections of the underlying measurable set.',
            'Sigma-finiteness is structural in standard product-measure construction; identify the finite-measure pieces explicitly.',
            'To expose failure of Fubini, look for conditionally convergent positive and negative parts with infinite total variation.',
            'After swapping integrals, compare the two iterated expressions to the original product-space integral rather than only to each other.'],
 'III/06': ['Compute \\(\\int |f|^p\\) and examine the singularity and tail separately; both regions must be integrable.',
            'Remember that \\(L^p\\) elements are equivalence classes: changing a function on a null set does not change its class.',
            'For a Cauchy sequence in \\(L^p\\), extract a rapidly Cauchy subsequence and use summable norm differences to build the limit.',
            'On finite-measure spaces, apply Hölder to compare \\(L^q\\) and \\(L^p\\) norms when \\(q>p\\).',
            'On infinite-measure spaces, test inclusions with power-law examples instead of assuming the finite-measure relation survives.',
            'Use truncation in size and support to approximate an \\(L^p\\) function by bounded finite-support functions.',
            'Norm convergence does not imply pointwise convergence of the whole sequence; look for an almost-everywhere convergent subsequence if '
            'needed.',
            'Check the endpoint \\(p=\\infty\\) separately: the essential supremum replaces an integral formula.'],
 'III/07': ['Choose conjugate exponents with \\(1/p+1/q=1\\) before applying Hölder; the exponent relation is part of the theorem.',
            'Normalize the functions by their \\(L^p\\) and \\(L^q\\) norms if you want a clean proof of Hölder.',
            'Apply Hölder to \\(|f+g|^{p-1}|f|\\) and \\(|f+g|^{p-1}|g|\\) to derive Minkowski.',
            'Interpolation exponents are determined by solving a convex combination of reciprocal exponents.',
            'Equality in Hölder requires proportionality of the appropriate powers of \\(|f|\\) and \\(|g|\\).',
            'Use Hölder to bound an integral operator by separating the kernel factor from the input function.',
            'At \\(p=1\\) or \\(p=\\infty\\), check the endpoint form rather than dividing by a vanishing conjugate exponent.',
            'Track every exponent through the estimate; a correct inequality with the wrong target exponent is not an interpolation result.'],
 'III/08': ['Egorov needs finite measure; choose the exceptional set first and make uniform convergence hold on its complement.',
            'Quantify the exceptional set by summing the measures of the bad sets in the proof.',
            'For a Vitali covering argument, extract a disjoint subfamily and compare the original set with an expanded union of those balls.',
            'Compute the level set \\(\\{|f|>\\lambda\\}\\) explicitly before evaluating the weak-\\(L^p\\) quantity.',
            'Weak-\\(L^p\\) control is \\(\\sup_{\\lambda>0}\\lambda^p\\mu(|f|>\\lambda)\\); optimize in \\(\\lambda\\) only after deriving the '
            'level-set measure.',
            'To separate weak and strong \\(L^p\\), use the borderline power \\(|x|^{-n/p}\\) on a suitable domain.',
            "Strong \\(L^p\\) implies weak \\(L^p\\) by Chebyshev's inequality; write that one-line estimate first.",
            'Do not use Egorov on an infinite-measure space without first restricting to a finite-measure subset.'],
 'III/09': ['Use parity and periodicity before computing any Fourier coefficient; many integrals vanish immediately.',
            'Write the partial sum as convolution with the Dirichlet kernel to see where localization and oscillation enter.',
            'At a jump discontinuity, the limit is the average of the two one-sided limits under the standard convergence hypotheses.',
            'Orthogonality of exponentials or sines/cosines turns coefficient computations into inner-product calculations.',
            'Parseval-type identities require the correct normalization of the basis and the period; check both constants.',
            'To compare pointwise and \\(L^2\\) convergence, separate what is controlled by norm from what is controlled at each point.',
            'Gibbs behavior is localized near jumps; inspect overshoot in scaled coordinates rather than expecting uniform convergence.',
            'For coefficient decay, integrate by parts only when the function has the needed regularity and periodic boundary compatibility.'],
 'III/10': ['Start from \\((f*g)(x)=\\int f(x-y)g(y)\\,dy\\) and check integrability before changing variables.',
            'The support of a convolution lies in the Minkowski sum of supports; prove inclusion before looking for equality.',
            'Use Fubini/Tonelli to justify associativity or commutativity rather than rearranging integrals formally.',
            "Young's inequality controls \\(\\|f*g\\|_r\\); choose exponents satisfying the correct reciprocal relation.",
            'For an approximate identity, verify unit mass, concentration near zero, and uniform \\(L^1\\) control.',
            'Split the approximation error into near and far regions so continuity handles one part and concentration handles the other.',
            'A mollifier smooths because derivatives fall on the smooth kernel; differentiate under the integral after checking justification.',
            'Keep support control explicit when using mollifiers on a domain; convolution near the boundary may leave the domain.'],
 'III/11': ['Fix the transform convention first; every scaling and inversion constant depends on it.',
            'For translation, substitute \\(y=x-a\\) and keep the resulting exponential phase factor.',
            'For modulation, multiply by the exponential first and read the frequency shift directly from the kernel.',
            'For scaling, change variables carefully and track the absolute determinant or scalar factor.',
            'Integration by parts moves differentiation in space to multiplication by frequency, with boundary terms killed by the hypotheses.',
            'Convolution becomes multiplication after transforming; use this before attempting a direct convolution integral.',
            "Check inversion only under the theorem's hypotheses; a formal inverse integral need not converge pointwise.",
            'Use symmetry and reality conditions to predict whether the transform is even, odd, real, or conjugate-symmetric.'],
 'III/12': ['Complete the square in the exponent and compare the transformed Gaussian with the original Gaussian family.',
            'Differentiate the Gaussian transform identity with respect to frequency to generate transforms of \\(x^k e^{-ax^2}\\).',
            'Multiplication by \\(x\\) in physical space becomes differentiation in frequency; apply the rule instead of reintegrating from scratch.',
            'Differentiate in the Gaussian parameter when justified to produce moments or heat-kernel identities.',
            'For the heat kernel, transform the PDE so the time evolution becomes a scalar ODE in frequency.',
            'Check mass conservation by integrating the Gaussian kernel or evaluating its transform at zero frequency.',
            'Spatial narrowing corresponds to frequency widening; derive the scaling law quantitatively.',
            'Normalize constants by testing the formula at a parameter value whose integral is already known.'],
 'III/13': ['Use Plancherel to move the inner product to frequency space before estimating the transformed expression.',
            'Define the \\(L^2\\) transform by density from Schwartz or \\(L^1\\cap L^2\\) functions, not by assuming the integral exists pointwise.',
            'Parseval is the inner-product form of Plancherel; polarize the norm identity if necessary.',
            'Two \\(L^2\\) functions that differ on a null set represent the same transform class, so avoid pointwise claims unless extra regularity '
            'is present.',
            'If the Fourier transform vanishes in \\(L^2\\), Plancherel forces the original function to have zero \\(L^2\\) norm.',
            'Multipliers bounded in frequency define bounded \\(L^2\\) operators; estimate by the essential supremum of the multiplier.',
            'For convolution in \\(L^2\\), verify the other factor provides enough integrability to make the product formula legitimate.',
            'Check normalization constants by applying Plancherel to a Gaussian, where both sides can be computed independently.'],
 'III/14': ['To prove Schwartz decay, bound \\(x^\\alpha\\partial^\\beta f(x)\\) uniformly for every pair of multi-indices.',
            'Differentiation preserves the Schwartz class because it only changes the derivative index in the seminorms.',
            'Polynomial multiplication preserves Schwartz decay by shifting the polynomial weight index.',
            'For the Fourier transform, integrate by parts to trade powers of frequency for derivatives of the original function.',
            'Compact support implies rapid decay only after Fourier transformation; it is not the same property as being Schwartz in physical space.',
            'Use the Schwartz seminorms to quantify convergence instead of relying on pointwise or uniform convergence alone.',
            'A function can be Schwartz without compact support; the Gaussian is the standard test case.',
            'To show a map is continuous on Schwartz space, estimate each output seminorm by finitely many input seminorms.'],
 'III/15': ['To construct a bump, start from the standard smooth function \\(e^{-1/(1-|x|^2)}\\) inside the unit ball and zero outside.',
            'Rescaling and translating a bump moves its support; compute the transformed support explicitly.',
            'Products of test functions remain test functions, with support contained in the intersection of the supports.',
            'Differentiation does not enlarge support; use this when preparing integration-by-parts arguments.',
            'Convergence in \\(C_c^\\infty\\) requires eventual support in one fixed compact set plus uniform convergence of every derivative.',
            'To build a cutoff equal to one on \\(K\\subset U\\), cover \\(K\\) by finitely many smaller neighborhoods and patch bumps.',
            'Compact support kills boundary terms because the test function and all needed derivatives vanish outside a bounded region.',
            'Do not confuse a sequence of supports shrinking or escaping to infinity with convergence in the test-function topology.'],
 'III/16': ['To verify a distribution, check linearity and estimate its action by finitely many test-function seminorms on each compact set.',
            'A locally integrable function acts by \\(T_f(\\phi)=\\int f\\phi\\); use local integrability because \\(\\phi\\) has compact support.',
            "The distributional derivative is defined by \\(T'(\\phi)=-T(\\phi')\\); the minus sign comes from integration by parts.",
            "For Heaviside, integrate \\(-\\int_0^\\infty \\phi'(x)\\,dx\\) and use compact support to evaluate the endpoint.",
            'To prove convergence of distributions, fix an arbitrary test function first and pass to the scalar limit of the pairings.',
            'Multiplication by a smooth function is defined by moving the multiplier onto the test function: \\((aT)(\\phi)=T(a\\phi)\\).',
            'For a differential operator, move every derivative onto the test function with the appropriate sign before simplifying.',
            'Do not evaluate a general distribution at a point; only its action on test functions is defined without extra structure.'],
 'III/17': ['A point lies outside the support if there is a neighborhood on which the distribution annihilates every test function.',
            'For \\(\\delta_{x_0}\\), test functions supported away from \\(x_0\\) vanish at the evaluation point.',
            'Derivatives of a Dirac mass have the same support as the Dirac mass even though their action involves derivatives of test functions.',
            'To identify singular support, first remove the largest open set on which the distribution agrees with a smooth function.',
            'Multiplication by a smooth function can shrink support to where both the multiplier and distribution are active.',
            'Use a cutoff supported in a small neighborhood to localize a distributional identity.',
            'Finite sums have support contained in the union of the individual supports; check whether cancellation can reduce it.',
            'For lower-dimensional concentrations, define the distribution by integration over the submanifold and inspect which test functions it '
            'can detect.'],
 'III/18': ['Temperedness means continuity on Schwartz space; estimate the pairing by a finite combination of Schwartz seminorms.',
            'A polynomially growing function is tempered because rapid decay of test functions makes the pairing absolutely integrable.',
            'Finite measures are tempered when their growth is controlled sufficiently to pair with Schwartz functions.',
            'Dirac masses are tempered because point evaluation is bounded by a Schwartz seminorm.',
            'Differentiation preserves temperedness by moving derivatives to the Schwartz test function.',
            'Multiplication by polynomials preserves temperedness because polynomial weights are built into the Schwartz seminorms.',
            'To show a distribution is not tempered, build Schwartz functions whose pairing grows faster than any finite seminorm bound permits.',
            'Keep the test-function space visible: a distribution may be valid on \\(C_c^\\infty\\) yet fail to extend continuously to Schwartz '
            'space.'],
 'III/19': ['Define \\(\\widehat T\\) by duality: pair \\(T\\) with the Fourier transform of the Schwartz test function.',
            'To transform a Dirac mass, evaluate the transformed test function at the support point and simplify the exponential.',
            'Distributional differentiation becomes multiplication by the frequency variable, with constants determined by the transform convention.',
            'Multiplication by \\(x\\) becomes differentiation in frequency; derive it by duality rather than formal pointwise manipulation.',
            'Polynomials transform into derivatives of Dirac masses, so expect singular frequency-space objects rather than ordinary functions.',
            'To solve a constant-coefficient equation, transform it and divide by the symbol only where that operation is distributionally '
            'meaningful.',
            'Check signs and \\(2\\pi\\) factors by applying the identity to one Schwartz test function and tracing the convention.',
            'Do not require classical integrability of the original object; tempered-distribution duality is exactly what replaces it.'],
 'III/20': ["To verify a weak derivative \\(g\\), test \\(\\int f\\phi'=-\\int g\\phi\\) for every compactly supported smooth \\(\\phi\\).",
            'For piecewise smooth functions, integrate by parts on each smooth piece and inspect the interface terms.',
            'A jump creates a Dirac contribution distributionally, so an \\(L^p\\) weak derivative may fail to exist even when a distributional '
            'derivative does.',
            'Weak derivatives are unique because a locally integrable function pairing to zero with every test function vanishes almost everywhere.',
            'Approximate by smooth functions and pass to the limit in the integration-by-parts identity when norm control permits.',
            'Classical differentiability implies weak differentiability under local integrability, but the converse only holds almost everywhere or '
            'in a weaker sense.',
            'Use difference quotients when the chapter provides them as a criterion for Sobolev weak differentiability.',
            'Keep boundary terms out of the definition by choosing compactly supported test functions inside the domain.'],
 'III/21': ['Compute every weak derivative required by the Sobolev norm before evaluating the norm itself.',
            'For \\(H^k\\), use the Hilbert norm built from \\(L^2\\) norms of derivatives up to order \\(k\\).',
            'Check dimension and exponent restrictions before invoking any Sobolev embedding; they determine the target space.',
            'Trace statements require boundary regularity and sufficient Sobolev exponent; verify both before assigning boundary values.',
            'Use completeness by showing a Cauchy sequence converges in each derivative component consistently.',
            'To prove an inequality, normalize by scaling first and see which exponent is forced by dimensional balance.',
            'Construct counterexamples near singular points to test whether a proposed function lies in \\(W^{1,p}\\).',
            'Do not infer continuity from Sobolev membership unless the relevant embedding theorem places the space inside a continuous-function '
            'class.'],
 'III/22': ['Extend or localize the function first if naive convolution would sample outside the domain.',
            'Choose a mollifier \\(\\rho_\\varepsilon\\) and use \\(f*\\rho_\\varepsilon\\) as the smooth approximation.',
            'Norm convergence follows by translation continuity plus averaging; write the convolution error as an average of translates.',
            'Use a cutoff after mollification when compact support inside the domain is required.',
            'Track weak derivatives through convolution: \\(D^\\alpha(f*\\rho_\\varepsilon)=(D^\\alpha f)*\\rho_\\varepsilon\\) in the weak sense.',
            'Boundary conditions may not survive ordinary mollification; modify the construction rather than assuming they do.',
            'Density in norm is stronger than pointwise approximation; estimate the actual target-space norm.',
            'Choose the approximation scale after fixing the error tolerance so each localization and smoothing error is controlled separately.'],
 'III/23': ['Multiply the PDE by a test function, integrate over the domain, and integrate derivatives off the unknown to obtain the weak form.',
            'Choose the trial space so the boundary condition is encoded structurally, for example by zero trace rather than a pointwise statement.',
            'Bound the bilinear form using Hölder, Cauchy--Schwarz, or Sobolev inequalities until it is continuous in the chosen norm.',
            'Coercivity requires a lower bound on \\(a(u,u)\\); use Poincaré-type control when the gradient norm alone appears.',
            'Only after boundedness and coercivity are verified should you invoke Lax--Milgram for existence and uniqueness.',
            'Interpret the right-hand side as a bounded linear functional on the test space and estimate its norm.',
            'To recover the strong PDE, integrate by parts backward only when the weak solution has enough additional regularity.',
            'Keep essential and natural boundary conditions distinct: they enter the variational formulation in different ways.'],
 'III/24': ['To verify \\(L\\Phi=\\delta\\), pair both sides with a test function and move \\(L\\) onto the test function.',
            'Fourier transform converts a constant-coefficient operator into multiplication by its symbol; solve algebraically in frequency space.',
            'After finding \\(\\widehat\\Phi\\), identify the inverse transform and track singular behavior at the source.',
            'A solution \\(u=\\Phi*f\\) is valid only when the convolution and differentiation operations are justified in the chosen '
            'function/distribution class.',
            'Use scaling of the operator to predict the homogeneity of the fundamental solution before computing constants.',
            'For Laplace-type operators, separate the singular point from the smooth region and verify harmonicity away from the source.',
            'Boundary conditions are not part of a free-space fundamental solution; do not confuse it with a Green function.',
            'Check the normalization constant by integrating the flux over a small sphere around the singularity or by testing against a bump.'],
 'III/25': ['Write the Green function as a free-space singular kernel plus a correction chosen to enforce the boundary condition.',
            'Verify the differential equation away from the pole and then verify the delta source distributionally at the pole.',
            'Check the boundary condition in the spatial variable separately from the source-variable dependence.',
            "Use Green's identity to derive the representation formula rather than guessing the integral kernel.",
            'Symmetry \\(G(x,y)=G(y,x)\\) follows from self-adjoint structure when the hypotheses hold; identify that structure first.',
            'Positivity requires a maximum-principle or energy argument; it is not automatic for every operator.',
            'In one dimension, solve the homogeneous ODE on each side of the source and match continuity plus derivative jump.',
            'Distinguish Dirichlet, Neumann, and periodic Green functions by the boundary/compatibility conditions they satisfy.'],
 'III/26': ['Choose one homogeneous solution satisfying the left boundary condition and another satisfying the right boundary condition.',
            'Compute the Wronskian; its nonvanishing is what lets the two homogeneous solutions normalize the kernel.',
            'Define the kernel piecewise on \\(x<\\xi\\) and \\(x>\\xi\\) using the two boundary-adapted solutions.',
            'Enforce continuity of the kernel at \\(x=\\xi\\) before imposing the derivative jump.',
            'Integrate the differential equation across a small interval around \\(\\xi\\) to derive the exact jump in the first derivative.',
            'Check the boundary conditions on the kernel before inserting it into the solution integral.',
            'For self-adjoint Sturm--Liouville problems, test whether the kernel should be symmetric after including the weight correctly.',
            'Periodic or Neumann problems may require compatibility conditions or removal of a zero mode; inspect the homogeneous kernel first.'],
 'III/27': ['Inspect the principal coefficient matrix or principal symbol; positive definiteness is the basic ellipticity test in the scalar '
            'second-order case.',
            'For a maximum principle, assume an interior positive maximum and evaluate the first and second derivative information there.',
            'Use the sign of the zeroth-order term exactly where the theorem requires it; changing that sign can destroy the conclusion.',
            'Uniqueness follows by applying the maximum principle to the difference of two solutions with zero boundary data.',
            'Comparison follows by applying the maximum principle to the difference between the candidate sub- and supersolutions.',
            'For a counterexample, alter ellipticity or the sign condition and look for an interior extremum that violates the expected bound.',
            'In weak settings, translate the maximum principle into an energy inequality for the positive part when that method is available.',
            'Keep boundary regularity and domain assumptions visible; the qualitative theorem is not independent of the setting.'],
 'III/28': ['Transform in the variables where the operator is translation invariant; leave the remaining variables untouched if separation is more '
            'natural.',
            'The Fourier transform turns spatial derivatives into multiplication by frequency, reducing the PDE to algebra or an ODE in time.',
            'For the heat equation, solve \\(\\partial_t\\widehat u=-|\\xi|^2\\widehat u\\) and then invert the transform.',
            'For the wave equation, solve the frequency-space oscillator and impose both initial displacement and velocity data.',
            'For elliptic resolvents, divide by the symbol only after checking zeros and the distribution/function space in which the multiplier '
            'acts.',
            'On bounded or periodic domains, replace the continuous Fourier transform by Fourier series or an eigenfunction expansion.',
            'Interpret large-frequency behavior of the multiplier as smoothing, damping, or amplification before estimating the inverse transform.',
            'Verify the final formula by checking the transformed equation and then the original initial or boundary conditions.']}

TRIAD = re.compile(
    r"(?P<exercise_block>\\begin\{exercise\}\\label\{exr:iii(?P<ch>\d{2})-(?P<idx>\d{2})\}(?P<exercise>.*?)\\end\{exercise\}\s*)"
    r"(?P<hint_block>\\begin\{hint\}(?P<hint>.*?)\\end\{hint\}\s*)"
    r"(?P<solution_block>\\begin\{solution\}(?P<solution>.*?)\\end\{solution\})",
    re.S,
)

def read_status(repo: Path):
    with (repo/"editorial/CHAPTER_STATUS.tsv").open("r",encoding="utf-8-sig",newline="") as f:
        return list(csv.DictReader(f,delimiter="\t"))

def paths_for_volume(repo: Path):
    out={}
    for row in read_status(repo):
        code=(row.get("chapter_code") or "").strip()
        if code in GOALS:
            if row.get("status")!="FROZEN" or row.get("next_action")!="COMPLETE":
                raise RuntimeError(f"{code}: expected FROZEN/COMPLETE")
            out[code]=repo/row["canonical_path"]
    missing=sorted(set(GOALS)-set(out))
    if missing:
        raise RuntimeError(f"missing Volume III status rows: {missing}")
    return out

def replace_goals(text: str, code: str) -> str:
    block=[
        r"\section*{Learning goals}",
        "After this chapter, the reader should be able to:",
        r"\begin{itemize}",
    ]
    block += [rf"\item {g}" for g in GOALS[code]]
    block += [r"\end{itemize}", ""]
    replacement="\n".join(block)
    pattern=re.compile(
        r"\\section\*\{Learning goals\}.*?(?=\\section\*\{Conceptual roadmap\})",
        re.S
    )
    if not pattern.search(text):
        raise RuntimeError(f"{code}: Learning goals block not found")
    return pattern.sub(lambda _: replacement,text,count=1)

def replace_hints(text: str, code: str):
    count=0
    chnum=int(code.split("/")[1])
    def repl(m):
        nonlocal count
        if int(m.group("ch"))!=chnum:
            return m.group(0)
        idx=int(m.group("idx"))
        hint=METHODS[code][idx-1]
        count += 1
        return (
            m.group("exercise_block")
            + "\\begin{hint}\n"
            + hint
            + "\n\\end{hint}\n"
            + m.group("solution_block")
        )
    out=TRIAD.sub(repl,text)
    return out,count

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--repo",required=True)
    ap.add_argument("--mode",choices=("goals","hints","all"),required=True)
    ap.add_argument("--start",type=int,default=1)
    ap.add_argument("--end",type=int,default=28)
    args=ap.parse_args()

    repo=Path(args.repo).resolve()
    paths=paths_for_volume(repo)
    summary=[]
    for n in range(args.start,args.end+1):
        code=f"III/{n:02d}"
        p=paths[code]
        text=p.read_text(encoding="utf-8-sig")
        before=text
        replaced=0
        if args.mode in ("goals","all"):
            text=replace_goals(text,code)
        if args.mode in ("hints","all"):
            text,replaced=replace_hints(text,code)
            if replaced!=8:
                raise RuntimeError(f"{code}: expected 8 hints, replaced {replaced}")
        if text!=before:
            p.write_text(text.rstrip()+"\n",encoding="utf-8")
        summary.append({"chapter_code":code,"changed":text!=before,"hints_replaced":replaced})
    print(json.dumps(summary,indent=2,ensure_ascii=False))
    return 0

if __name__=="__main__":
    raise SystemExit(main())
